### ISSUE TITLE
Long-running Assemble Step

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#349] opened 2020-05-17 23:00 UTC
I set `--steps Assemble ` and put a limit of 18 hours thinking that I was providing plenty of buffer. However, on this dataset sequenced at Garvan Institute's Genome.One, I get most tasks reaching the limit and being terminated. A few which are still running and about to be destroyed are:

```
%CPU  WallTime  Time Lim     RSS    mem memlim cpus
  97  15:52:05  18:00:00  60.6GB 60.6GB 90.0GB    8
 100  17:06:01  18:00:00  43.5GB 43.5GB 90.0GB    8
  98  15:43:15  18:00:00  47.2GB 47.2GB 90.0GB    8
```

It's not swapping or anything - CPU usage is almost 100%. Another dataset sequenced by AGRF Melbourne has similar read depth and Assemble stage took, on average, 3 hours.

```
structuralAssemble.pbs.o5463124:   Walltime requested: 13:00:00            Walltime Used: 01:32:59        
structuralAssemble.pbs.o5463127:   Walltime requested: 13:00:00            Walltime Used: 02:58:38        
structuralAssemble.pbs.o5463130:   Walltime requested: 13:00:00            Walltime Used: 01:40:20        
structuralAssemble.pbs.o5463133:   Walltime requested: 13:00:00            Walltime Used: 01:40:42
         ...                                  ...                         ...
```

Having a casual look in IGV at one of the above long-running Genome.One samples shows it looks quite ordinary.

![image](https://user-images.githubusercontent.com/631218/82161861-913e5180-98e3-11ea-83c8-a10cdd7a1115.png)

Both datasets use hg38 reference genome with alt contigs and GRIDSS version 2.9.1 and have read depths similar to Hartwig Medical's.

Should I delete all of these working directories and start again or leave them and GRIDSS will find the right starting point to resume from within the Assembly stage, after the lengthy running issue is resolved? Does troubleshooting need a pair of BAM files to be shared via CloudStor, perhaps?

**Comment by d-cameron** [comment] 2020-05-18 06:45
You could attach the full log file?

Are you running mulitple `--steps Assemble` processes in parallelel on the same data? If you are, you must set `--jobindex` and `--jobnodes` for each instance, otherwise they'll all be doing a full assembly and overwriting each others' results.

**Comment by DarioS** [comment] 2020-05-18 07:00
Good point. It is attached. No, I am running different patients as separate jobs. One other important point I forgot to mention: one dataset has an average of 3 somatic mutations per megabase but the other has 300 somatic mutations per megabase. How does GRIDSS assembly scale with mutation burden? I imagine that a high burden makes assembly hard to do.

[gridss.full.20200517_174636.gadi-cpu-clx-0850.gadi.nci.org.au.4742.log](https://github.com/PapenfussLab/gridss/files/4642507/gridss.full.20200517_174636.gadi-cpu-clx-0850.gadi.nci.org.au.4742.log)

**Comment by d-cameron** [comment] 2020-05-18 07:23
Nothing catastrophic in the log file but that is definitely slow assembling:

133kb/s/thread HG002@60x (E5-2690)
33kb/s/thread  Hartwig COLO829@40+100X (E5-2690)
5kb/s/thread   your sample

TMB doesn't really make a difference since the vast majority of assembly time is spent assembling noise. That said, sequencing quality and library fragment size do have a significant impact on assembly. The log indicates that the assembly complexity safety check was triggered quite a few times in your sample (grep "Safety mode initiated" full.log) which is consistent with the assembler having a more difficult time on your data.

**Comment by d-cameron** [comment] 2020-05-18 07:31
> Should I delete all of these working directories and start again or leave them and GRIDSS will find the right starting point to resume from within the Assembly stage

Rerunning will continue where it left off (with up to 3h of work lost due to your 50Mb chunk size).


> Does troubleshooting need a pair of BAM files to be shared via CloudStor, perhaps?

I would need to see the data to know why it's running slowly as there's technically not actually anything wrong, it's just slow. If you do upload, I'd only need the contents of the input working directories and the config file - not the full BAMs. A copy of your reference genome would also save me having to chase it down.

If you can, run `visualvm` or `jvisualvm` (you'll need to do ssh -X forwarding as it's a GUI application) on the node doing the assembly to have a look at how the process is fairing. Is GC% less than 1%? Does the thread utilisation seem reasonable?

**Comment by DarioS** [comment] 2020-05-18 09:00
Yes, there are some big ones in this dataset

```
grep -c "Safety mode initiated" gridss.full.2020.*
...
gridss.full.20200517_174636.gadi-cpu-clx-0850.gadi.nci.org.au.4742.log:670
gridss.full.20200517_175553.gadi-cpu-clx-2144.gadi.nci.org.au.49248.log:1006
gridss.full.20200517_180145.gadi-cpu-clx-0939.gadi.nci.org.au.22981.log:1357
...
```

I have not used Java in about 8 years, so I'll send you one working directory, the genome and the config file via CloudStor. Thanks for checking this.

**Comment by d-cameron** [comment] 2020-06-12 04:54
Are you missing the `INPUT.gridss.working/INPUT.coverage.blacklist.bed` file in your input working directory? If it's not there, GRIDSS attemptes to load it every read (due bug in blacklist caching logic) which makes assembly very slow.

**Comment by DarioS** [comment] 2020-06-12 05:00
No, it's in the folder. I attach the file (extension renamed because of GitHub rules prohibit .bed).
[CSCC_0019-P1.final.bam.coverage.blacklist.txt](https://github.com/PapenfussLab/gridss/files/4768850/CSCC_0019-P1.final.bam.coverage.blacklist.txt)

**Comment by d-cameron** [comment] 2020-06-21 16:35
Root cause finally found and fixed.

The `NonReferenceContigAssembler	Sanity check failure: non-empty graph with no contigs called` error messages were an indirect symptom of the problem and these should be fixed too.

**Closed by d-cameron** 2020-06-21 16:35 UTC
