### ISSUE TITLE
Somatic filtering error: Can't subset elements that don't exist

### ISSUE THREAD

**Issue by willhooper** [PapenfussLab/gridss#435] opened 2020-12-22 19:31 UTC
Hi, 

When running the somatic filter on hg38 somatic single-sample GRIDSS results, I've been getting the following error (this doesn't occur on every sample). If it helps, I can provide the VCF in question: 

```
2020-12-21 14:51:38 Reading vcf
Tumour samples: COLO-829-NovaSeq-Rep1-60xTumor-20xNormal.final.bam.sv.bam
Matched normals: COLO-829BL-NovaSeq-Rep1-40x
2020-12-21 14:53:53 Parsing single breakends 
2020-12-21 14:54:07 Calculating single breakend VAF 
2020-12-21 14:54:18 Filtering single breakends 
2020-12-21 14:54:22 Loading from cache  
2020-12-21 14:54:29 Parsing breakpoints 
2020-12-21 14:54:33 Calculating breakpoint VAF 
2020-12-21 14:54:34 Filtering breakpoints 
2020-12-21 14:54:35 Loading from cache  
2020-12-21 14:55:12 Calculating transitive links 
`summarise()` ungrouping output (override with `.groups` argument)
`summarise()` ungrouping output (override with `.groups` argument)
2020-12-21 14:55:19 Calculating assembly links 
`summarise()` ungrouping output (override with `.groups` argument)
2020-12-21 14:55:20 Calculating bebe insertion links 
2020-12-21 14:55:20 Calculating bebp insertion links 
2020-12-21 14:55:21 Calculating simple inversions 
2020-12-21 14:55:21 Calculating dsb links 
2020-12-21 14:55:21 Removing duplicated/conflicting links 
Error: Can't subset elements that don't exist.
✖ Location 1 doesn't exist.
ℹ There are only 0 elements.
Backtrace:
     █
  1. ├─`%>%`(...)
  2. │ ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  3. │ └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  4. │   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5. │     └─`_fseq`(`_lhs`)
  6. │       └─magrittr::freduce(value, `_function_list`)
  7. │         └─function_list[[i]](value)
  8. │           ├─dplyr::mutate(...)
  9. │           └─dplyr:::mutate.data.frame(...)
 10. │             └─dplyr:::mutate_cols(.data, ...)
 11. │               ├─base::withCallingHandlers(...)
 12. │               └─mask$eval_all_mutate(dots[[i]])
 13. ├─base::.signalSimpleWarning(...)
 14. │ └─base::withRestarts(...)
 15. │   └─base:::withOneRestart(expr, restarts[[1L]])
 16. │     └─base:::doWithOneRestart(return(expr), restart)
 17. └─(funct
Execution halted
```

Thanks,
Will

**Comment by d-cameron** [comment] 2020-12-24 02:59
Yes, please supply a VCF that reproduces this issue.

**Comment by willhooper** [comment] 2020-12-28 15:57
I've emailed you with a google drive link to vcf -- let me know if you don't get the email for some reason.

**Comment by d-cameron** [comment] 2021-01-01 13:45
Ok, so I'm unable to reproduce the issue with that VCF so I'm starting to think it's either a R package, or `gridss_somatic_filter.R`/`libgridss.R` versioning issue.

```
$ md5sum *.R
cd406597b819e45fc3dfc96ec304e6c4  gridss.config.R
5d81984745bd6eb222ec162ec1626a27  gridss_somatic_filter.R
371864a545442e9a9f30ec9847689ac8  libgridss.R
```
and the R environment is:
```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] BSgenome.Hsapiens.UCSC.hg38_1.4.3 BSgenome_1.56.0                   stringdist_0.9.5.5                testthat_2.3.2                    StructuralVariantAnnotation_1.4.0
 [6] rtracklayer_1.48.0                VariantAnnotation_1.34.0          Rsamtools_2.4.0                   SummarizedExperiment_1.18.1       GenomicRanges_1.40.0             
[11] GenomeInfoDb_1.24.2               Biobase_2.48.0                    Biostrings_2.56.0                 XVector_0.28.0                    DelayedArray_0.14.0              
[16] matrixStats_0.56.0                IRanges_2.22.2                    S4Vectors_0.26.1                  BiocGenerics_0.34.0               forcats_0.5.0                    
[21] stringr_1.4.0                     dplyr_1.0.0                       purrr_0.3.4                       readr_1.3.1                       tidyr_1.1.0                      
[26] tibble_3.0.1                      ggplot2_3.3.1                     tidyverse_1.3.0                   argparser_0.6                    

loaded via a namespace (and not attached):
 [1] nlme_3.1-148             bitops_1.0-6             fs_1.4.1                 lubridate_1.7.9          bit64_0.9-7              progress_1.2.2           httr_1.4.1              
 [8] tools_4.0.0              backports_1.1.7          R6_2.4.1                 DBI_1.1.0                colorspace_1.4-1         withr_2.2.0              tidyselect_1.1.0        
[15] prettyunits_1.1.1        bit_1.1-15.2             curl_4.3                 compiler_4.0.0           cli_2.0.2                rvest_0.3.5              xml2_1.3.2              
[22] scales_1.1.1             askpass_1.1              rappdirs_0.3.1           digest_0.6.25            pkgconfig_2.0.3          dbplyr_1.4.4             rlang_0.4.6             
[29] readxl_1.3.1             rstudioapi_0.11          RSQLite_2.2.0            generics_0.0.2           jsonlite_1.6.1           BiocParallel_1.22.0      RCurl_1.98-1.2          
[36] magrittr_1.5             GenomeInfoDbData_1.2.3   Matrix_1.2-18            fansi_0.4.1              Rcpp_1.0.4.6             munsell_0.5.0            lifecycle_0.2.0         
[43] stringi_1.4.6            zlibbioc_1.34.0          BiocFileCache_1.12.0     grid_4.0.0               blob_1.2.1               crayon_1.3.4             lattice_0.20-41         
[50] haven_2.3.1              GenomicFeatures_1.40.0   hms_0.5.3                pillar_1.4.4             biomaRt_2.44.1           reprex_0.3.0             XML_3.99-0.3            
[57] glue_1.4.1               modelr_0.1.8             vctrs_0.3.1              cellranger_1.1.0         gtable_0.3.0             openssl_1.4.1            assertthat_0.2.1        
[64] broom_0.5.6              GenomicAlignments_1.24.0 AnnotationDbi_1.50.1     memoise_1.1.0            ellipsis_0.3.1         
```

How does this differ from your environment?

**Comment by d-cameron** [comment] 2021-01-01 13:49
Duplicate of #390 and fixed on 2020-09-03 so should be working from v2.10.0 onwards.

**Closed by d-cameron** 2021-01-01 13:49 UTC

**Comment by willhooper** [comment] 2021-01-04 22:09
Here's my environment.. suspecting this might be an issue with one of the tidyverse packages but I'll have to do some digging

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /nfs/sw/R/R-4.0.0/lib64/R/lib/libRblas.so
LAPACK: /nfs/sw/R/R-4.0.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] BSgenome.Hsapiens.UCSC.hg38_1.4.3 BSgenome_1.57.6
 [3] stringdist_0.9.6.3                testthat_3.0.1
 [5] StructuralVariantAnnotation_1.6.0 rtracklayer_1.50.0
 [7] VariantAnnotation_1.35.3          Rsamtools_2.5.3
 [9] SummarizedExperiment_1.19.6       GenomicRanges_1.41.6
[11] GenomeInfoDb_1.25.11              Biobase_2.49.1
[13] Biostrings_2.57.2                 XVector_0.29.3
[15] DelayedArray_0.15.7               Matrix_1.2-18
[17] matrixStats_0.56.0                IRanges_2.23.10
[19] S4Vectors_0.27.12                 BiocGenerics_0.35.4
[21] forcats_0.5.0                     stringr_1.4.0
[23] dplyr_1.0.2                       purrr_0.3.4
[25] readr_1.3.1                       tidyr_1.1.2
[27] tibble_3.0.3                      ggplot2_3.3.2
[29] tidyverse_1.3.0                   argparser_0.6

loaded via a namespace (and not attached):
 [1] bitops_1.0-6             fs_1.5.0                 lubridate_1.7.9
 [4] bit64_4.0.5              progress_1.2.2           httr_1.4.2
 [7] rprojroot_1.3-2          tools_4.0.0              backports_1.1.9
[10] R6_2.4.1                 DBI_1.1.0                colorspace_1.4-1
[13] withr_2.3.0              tidyselect_1.1.0         prettyunits_1.1.1
[16] bit_4.0.4                curl_4.3                 compiler_4.0.0
[19] cli_2.2.0                rvest_0.3.6              xml2_1.3.2
[22] desc_1.2.0               scales_1.1.1             askpass_1.1
[25] rappdirs_0.3.1           digest_0.6.25            pkgconfig_2.0.3
[28] dbplyr_1.4.4             rlang_0.4.10             readxl_1.3.1
[31] rstudioapi_0.11          RSQLite_2.2.0            generics_0.0.2
[34] jsonlite_1.7.1           BiocParallel_1.23.2      RCurl_1.98-1.2
[37] magrittr_1.5             GenomeInfoDbData_1.2.3   Rcpp_1.0.5
[40] munsell_0.5.0            fansi_0.4.1              lifecycle_0.2.0
[43] stringi_1.4.6            zlibbioc_1.35.0          BiocFileCache_1.13.1
[46] grid_4.0.0               blob_1.2.1               crayon_1.3.4
[49] lattice_0.20-41          haven_2.3.1              GenomicFeatures_1.41.3
[52] hms_0.5.3                ps_1.3.4                 pillar_1.4.6
[55] pkgload_1.1.0            biomaRt_2.45.2           reprex_0.3.0
[58] XML_3.99-0.5             glue_1.4.2               modelr_0.1.8
[61] vctrs_0.3.4              cellranger_1.1.0         gtable_0.3.0
[64] openssl_1.4.2            assertthat_0.2.1         broom_0.7.0
[67] GenomicAlignments_1.25.3 AnnotationDbi_1.51.3     memoise_1.1.0
```

**Comment by willhooper** [comment] 2021-01-05 17:54
Installing `dpylr 1.0.0` and `stringdist 0.9.5.5` seemed to resolve the issue. Thanks for your help in sorting this out!
