### ISSUE TITLE
Error during assembly of chromosome...

### ISSUE THREAD

**Issue by icanwinwyz** [PapenfussLab/gridss#350] opened 2020-05-18 06:15 UTC
Hi,
Thanks for developing such a great tool! I got some errors during assembly of chromosome. However, it looks like the process is able to proceed. I am wondering what is reason for these errors? and will the errors affect the final results? Is this caused by the regions with "N" in the genome? Thanks. 

The errors are shown below:

INFO    2020-05-17 22:40:10     AssemblyEvidenceSource  Starting assembly on chunk 3 (chr1:30000001-chr1:40000000)
INFO    2020-05-17 22:40:10     AssemblyEvidenceSource  Starting assembly on chunk 6 (chr1:60000001-chr1:70000000)
INFO    2020-05-17 22:40:10     AssemblyEvidenceSource  Starting assembly on chunk 7 (chr1:70000001-chr1:80000000)
INFO    2020-05-17 22:40:10     AssemblyEvidenceSource  Starting assembly on chunk 8 (chr1:80000001-chr1:90000000)
INFO    2020-05-17 22:40:10     AssemblyEvidenceSource  Starting assembly on chunk 9 (chr1:90000001-chr1:100000000)
INFO    2020-05-17 22:41:31     NonReferenceContigAssembler     Sanity check failure: non-empty graph with no contigs called chr1
INFO    2020-05-17 22:41:31     PositionalAssembler     Error during assembly of chromosome chr1 (0 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.RuntimeException: Sanity check failure: non-empty graph with no contigs called chr1
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:279)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:195)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:76)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:234)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:103)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:61)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:238)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:196)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:98)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by d-cameron** [comment] 2020-05-18 06:39
If GRIDSS generated a `gridss_minimal_reproduction_data_for_error_1.zip` file then yes, please upload as it means I can reproduced the problem locally and fix it.

There's an edge case in the streaming assembly algorithm isn't behaving correctly but unless I have a minimal reproduction data set, it's really really difficult to debug. I have a lot of optional debugging sanity check that I can turn on to identify assembly inconsistencies but they make the assembly somewhere in the region of 100-10,000x slower (since they check the entire graph whenever anything changes) so it'd take days/weeks to actually hit the error condition when millions of reads need to get processed first.

**Comment by d-cameron** [comment] 2020-05-18 06:41
> and will the errors affect the final results?

No, the inconsistent state was detected and fixed before the error affected the assembly output. 

Technically, it's possible that it changed the assembly results before the error was detected,, but it'd only be one or two reads different so the impact would be very small.

**Comment by d-cameron** [comment] 2020-06-21 16:35
` NonReferenceContigAssembler Sanity check failure: non-empty graph with no contigs` fixed in dev.

**Closed by d-cameron** 2020-06-21 16:35 UTC
