### ISSUE TITLE
Error loop in PositionalAssembler

### ISSUE THREAD

**Issue by austinhpatton** [PapenfussLab/gridss#286] opened 2020-01-09 20:33 UTC
Hi there,

I'm currently trying to call SVs for ~ 50 samples, and the pipeline has proceeded smoothly up until the positional assembler, at which point I hit an error loop. Specifically, I get the following error messages: 

> WARNING 2020-01-09 12:25:46     PositionalAssembler     Error during assembly of chromosome chr1_GL834469_random (2370 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:25:46     PositionalAssembler     Error during assembly of chromosome chr1_GL834418_random (1646 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:25:46     PositionalAssembler     Error during assembly of chromosome chr1_GL834511_random (1733 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:25:46     PositionalAssembler     Error during assembly of chromosome chr1_GL834445_random (3414 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:25:47     PositionalAssembler     Error during assembly of chromosome chr1_GL834465_random (4503 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:25:47     PositionalAssembler     Error during assembly of chromosome chr1_GL834495_random (2508 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:25:47     PositionalAssembler     Error during assembly of chromosome chr1_GL834507_random (1823 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:26:20     PositionalAssembler     Error during assembly of chromosome chr1_GL834475_random (2652 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:26:21     PositionalAssembler     Error during assembly of chromosome chr1_GL834453_random (2074 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:26:21     PositionalAssembler     Error during assembly of chromosome chr1_GL834481_random (2539 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:26:21     PositionalAssembler     Error during assembly of chromosome chr1_GL834418_random (1646 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:26:21     PositionalAssembler     Error during assembly of chromosome chr1_GL834451_random (2761 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:26:21     PositionalAssembler     Error during assembly of chromosome chr1_GL834412_random (4049 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:26:21     PositionalAssembler     Error during assembly of chromosome chr1_GL834463_random (2348 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:26:21     PositionalAssembler     Error during assembly of chromosome chr1_GL834484_random (2387 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.NullPointerException
WARNING 2020-01-09 12:26:21     PositionalAssembler     Error during assembly of chromosome chr1_GL834501_random (2772 reads in graph). Attempting recovery by rebuilding assembly graph.

This goes on for ~10 or so more contigs before repeating itself. This has continued for several days. 

It's unclear from the error message whether this is due to one particular sample, or whether this issue is persistent across all *.sv.bam files the software is accessing. 

I'm using version 2.7.3.

If there is anything I can do to clarify, please let me know!

Austin

**Comment by d-cameron** [comment] 2020-01-23 00:24
>If there is anything I can do to clarify, please let me know!

This definitely looks like an issue with the asssembly. Each of these errors indicates that the assembler has encountered an internal data inconsistencies, rebuilt the assembly graph, then successfully continued with assembly. The fact that you're getting this isssue at all indicates a bug in the assembler and/or data consistency issue with your input data.

>It's unclear from the error message whether this is due to one particular sample, or whether this issue is persistent across all *.sv.bam files the software is accessing.

The assembly step is a joint assembly across all samples. A per-sample breakdown of supporting reads is tracked but it's still a single all-sample assembly. It's theoretically possible that each input assembles fine in isolation but only joint assembly fails.

> Specifically, I get the following error messages:

Do you get stack trace with the NullPointerException or just the single-line error?

Are you able to create and attach a minimal data set for reproduction of this issue? Minimal data required is all files in the _input_.gridss.working directories, with the *.sv.bam filtered to just the region of interest (e.g. chr1_GL834469_random). Actual input files are not required as all the reads GRIDSS considers are in the .sv.bam files. Filter to just the shortest contig for which you get an error; they all look like the same underlying issue.

> If there is anything I can do

- Wait for assembly to complete. If it's already been running for several days this might take a while. Recent versions of GRIDSS do support distributing assembly across multiple nodes so this approach may be fine if you're able to throw more compute resources at it.

or 

- Attach a minimal repo data set and I can fix the issue.

**Comment by d-cameron** [comment] 2020-03-06 06:11
Could be fixed by 4f1aee7.

**Comment by d-cameron** [comment] 2020-03-13 00:42
Should be fixed in 2.8.1. Please reopen if this is not the case.

**Closed by d-cameron** 2020-03-13 00:42 UTC
