### ISSUE TITLE
Error in somatic filter

### ISSUE THREAD

**Issue by sohnjangil** [PapenfussLab/gridss#437] opened 2021-01-10 08:22 UTC
Hi.

I am Jang-il Sohn in Hanyang University.
gridss_somatic_filter.R looks like having some bugs.
It did not make somatic filter in 5 tumor samples out of 21.

I saw previous issues about similar error, and I tried, but it did not work.
To solve this issue, I reinstalled dplyr, but it did not work, too.
The below lines are the log of one of the samples.

```
$ cat 7.MM9_gridss.gridss_somatic_filter.log

Attaching package: ‘Matrix’

The following object is masked from ‘package:S4Vectors’:

    expand

The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack


Attaching package: ‘MatrixGenerics’

The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars

Test passed 🥇
Test passed 🎊
No reference genome supplied using --ref. Not performing variant equivalence checks.
2021-01-10 07:13:33 Reading 7.MM9_gridss.vcf.gz
Tumour samples: tumor
Matched normals: normal
2021-01-10 07:15:19 Parsing single breakends 7.MM9_gridss.vcf.gz
2021-01-10 07:15:30 Calculating single breakend VAF 7.MM9_gridss.vcf.gz
2021-01-10 07:15:37 Filtering single breakends 7.MM9_gridss.vcf.gz
2021-01-10 07:15:43 Parsing breakpoints 7.MM9_gridss.vcf.gz
2021-01-10 07:15:50 Calculating breakpoint VAF 7.MM9_gridss.vcf.gz
2021-01-10 07:15:57 Filtering breakpoints 7.MM9_gridss.vcf.gz
2021-01-10 07:16:18 Calculating transitive links 7.MM9_gridss.vcf.gz
`summarise()` ungrouping output (override with `.groups` argument)
2021-01-10 07:16:19 Calculating assembly links 7.MM9_gridss.vcf.gz
`summarise()` ungrouping output (override with `.groups` argument)
2021-01-10 07:16:19 Calculating bebe insertion links 7.MM9_gridss.vcf.gz
2021-01-10 07:16:20 Calculating bebp insertion links 7.MM9_gridss.vcf.gz
2021-01-10 07:16:20 Calculating simple inversions 7.MM9_gridss.vcf.gz
2021-01-10 07:16:20 Calculating dsb links 7.MM9_gridss.vcf.gz
2021-01-10 07:16:21 Removing duplicated/conflicting links 7.MM9_gridss.vcf.gz
Error: Can't subset elements that don't exist.
✖ Location 1 doesn't exist.
ℹ There are only 0 elements.
Backtrace:
     █
  1. ├─`%>%`(...)
  2. ├─dplyr::filter(...)
  3. ├─dplyr::mutate(...)
  4. ├─dplyr:::mutate.data.frame(...)
  5. │ └─dplyr:::mutate_cols(.data, ...)
  6. │   ├─base::withCallingHandlers(...)
  7. │   └─mask$eval_all_mutate(dots[[i]])
  8. ├─base::.signalSimpleWarning(...)
  9. │ └─base::withRestarts(...)
 10. │   └─base:::withOneRestart(expr, restarts[[1L]])
 11. │     └─base:::doWithOneRestart(return(expr), restart)
 12. └─(function (w) ...
 13.   ├─rlang::warn(...)
 14.   │ └─rlang:::validate_signal_message(message, class)
 15.   └─dplyr:::cnd_bullet_cur_group_label()
 16.     └─dplyr:::cur_group_label()
 17.       ├─base::paste0("group ", cur_group_id(), ": ", group_labels_details(cur_group()))
 18.       ├─dplyr:::group_labels_details(cur_group())
 19.       │ ├─glue::glue_collapse(...)
 20.       │ └─dplyr:::map2_chr(...)
 21.       │   ├─base::as.vector(map2(.x, .y, .f, ...), "character")
 22.       │   └─dplyr:::map2(.x, .y, .f, ...)
 23.       │     └─base::mapply(.f, .x, .y, MoreArgs = list(...), SIMPLIFY = FALSE)
 24.       └─dplyr::cur_group()
 25.         └─peek_mask("cur_group()")$current_key()
 26.           └─vctrs::vec_slice(private$keys, self$get_current_group())
 27.             └─(function () ...
 28.               └─vctrs:::stop_subscript_oob(...)
 29.                 └─vctrs:::stop_subscript(...)
Execution halted
```
I tried gripss also, but its the number of lines of gripss filtered vcf file was quite different.
I need gridss_somatic_filter.R, not gripss.

If you need unfiltered vcf file, I can send it to you via e-mail.

Jang-il Sohn

**Comment by d-cameron** [comment] 2021-01-10 08:47
Are you using this latest version of the filtering script?

Also, it the vcf file would be very useful as gripss is a port of the
script so I'd like to investigate the differences.

**Comment by sohnjangil** [comment] 2021-01-10 08:58
Thank you for your quick reply.

Yes, I believe that I am using the latest version of
gridss_somatic_filter.R.
I am sending the R script with my vcf file.

--- Jang-il Sohn
 7.MM9_gridss.vcf.gz
<https://drive.google.com/file/d/13u1envQvbTpHiTIDTfF3Z844rA3H1u44/view?usp=drive_web>
 7.MM9_gridss.vcf.gz.tbi
<https://drive.google.com/file/d/1JQEUHGXirfXAyerNc5NB4r76j6--gRUI/view?usp=drive_web>

2021년 1월 10일 (일) 오후 5:47, Daniel Cameron <notifications@github.com>님이 작성:

> Are you using this latest version of the filtering script?
>
> Also, it the vcf file would be very useful as gripss is a port of the
> script so I'd like to investigate the differences.
>

**Comment by sohnjangil** [comment] 2021-01-10 09:00
I missed gridss_somatic_filter.R script, and I am sending it.

--- Jang-il Sohn

2021년 1월 10일 (일) 오후 5:47, Daniel Cameron <notifications@github.com>님이 작성:

> Are you using this latest version of the filtering script?
>
> Also, it the vcf file would be very useful as gripss is a port of the
> script so I'd like to investigate the differences.
>

**Comment by d-cameron** [comment] 2021-02-22 16:12
Duplicate of #390

**Closed by d-cameron** 2021-02-22 16:12 UTC

**Comment by sohnjangil** [comment] 2021-02-23 01:45
Actually, I solved it.
The issue was related to Bioconductor and BiocManager.
After reinstallation of them, the somatic filter works well.
However, there is still one more issue.
Approximately 1 of 10, GRIDSS failed with the last version, so I had to re-run the samples (failed with 2.10.2 version) using 2.7.3 version.

**Comment by d-cameron** [comment] 2021-02-23 04:33
Please raise a seperate issue for the failing run and include the full log message (`gridss.full.*.log`) from one of the failing samples.

I'm working on the next release right now so if I have a reproducable test case I'll be able to get a fixed version out by next week.
