### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by SteveMarshallFSP** [PapenfussLab/gridss#299] opened 2020-02-15 20:02 UTC
Hi

I'm running the most recent version 2.7.3.
I'm trying to detect where a mobile element is integrated into the human genome. I've created a custom db GRCh38 + transposon sequence to first align against. Then run gridss but I get this error message when it does the assembly...

Sat Feb 15 19:58:49 UTC 2020    Start assembly  /scratch/workspace/gridss/output/mobile_elementX_assembly.bam
Sat Feb 15 19:58:49 UTC 2020    AssembleBreakends       /scratch/workspace/gridss/output/mobile_elementX_assembly.bam     job 0   total jobs 1
"$timecmd java -Xmx$jvmheap $jvm_args -Dgridss.gridss.output_to_temp_file=true -cp $gridss_jar gridss.AssembleBreakends JOB_INDEX=$jobindex JOB_NODES=$jobnodes TMP_DIR=$workingdir WORKING_DIR=$workingdir REFERENCE_SEQUENCE=$reference WORKER_THREADS=$threads O=$assembly $input_args $blacklist_arg $config_args $picardoptions" command completed with exit code 1.

ERROR	2020-02-15 19:37:02	SupportNodeIterator	Error: kmer in evidence TLaVTCNwDi865Lnh5rqNFfy1jHLMrnf8 of read M06186:7:000000000-CF8LC:1:2116:19993:15999 (chr22:44277248 19S237M45S) out of bounds. Kmer support starts at 44277080 which is more than 399 before the breakpoint start position at (21):44277555(44277484-44277626)>
ERROR	2020-02-15 19:37:02	SupportNodeIterator	Error: kmer in evidence TLaVTCNwDi865Lnh5rqNFfy1jHLMrnf8 of read M06186:7:000000000-CF8LC:1:2116:19993:15999 (chr22:44277248 19S237M45S) out of bounds. Kmer support starts at 44277081 which is more than 399 before the breakpoint start position at (21):44277555(44277484-44277626)>
ERROR	2020-02-15 19:37:02	SupportNodeIterator	Error: kmer in evidence TLaVTCNwDi865Lnh5rqNFfy1jHLMrnf8 of read M06186:7:000000000-CF8LC:1:2116:19993:15999 (chr22:44277248 19S237M45S) out of bounds. Kmer support starts at 44277082 which is more than 399 before the breakpoint start position at (21):44277555(44277484-44277626)>
ERROR	2020-02-15 19:37:02	SupportNodeIterator	Error: kmer in evidence TLaVTCNwDi865Lnh5rqNFfy1jHLMrnf8 of read M06186:7:000000000-CF8LC:1:2116:19993:15999 (chr22:44277248 19S237M45S) out of bounds. Kmer support starts at 44277083 which is more than 399 before the breakpoint start position at (21):44277555(44277484-44277626)>
ERROR	2020-02-15 19:37:02	SupportNodeIterator	Error: kmer in evidence TLaVTCNwDi865Lnh5rqNFfy1jHLMrnf8 of read M06186:7:000000000-CF8LC:1:2116:19993:15999 (chr22:44277248 19S237M45S) out of bounds. Kmer support starts at 44277084 which is more than 399 before the breakpoint start position at (21):44277555(44277484-44277626)>
ERROR	2020-02-15 19:37:02	NonReferenceContigAssembler	Sanity check failure: found path with no support (chr22:44277071)
ERROR	2020-02-15 19:37:02	PositionalAssembler	Error assembling chr22. Please raise an issue at https://github.com/PapenfussLab/gridss/issues
java.lang.RuntimeException: Sanity check failure: found path with no support (chr22:44277071)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:616)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:208)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:238)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:172)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:83)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:245)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:110)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:147)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:118)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:68)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:198)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
ERROR	2020-02-15 19:37:02	AssemblyEvidenceSource	Error assembling chunk 287 (chr22:40762457-chr22:50762456)
java.lang.RuntimeException: Sanity check failure: found path with no support (chr22:44277071)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:616)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:208)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:238)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:172)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:83)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:245)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:110)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:147)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:118)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:68)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:198)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by d-cameron** [comment] 2020-02-17 00:19
Was a miinimal reproduction export file generated? The file should be called `gridss_minimal_reproduction_data_for_error_1.zip` and should be in a subdirectory of the working directory. Please attach if you can find it so I can reproduce the error locally.

**Comment by d-cameron** [comment] 2020-02-17 00:26
Failing that, could you post all SAMRecords for the read `M06186:7:000000000-CF8LC:1:2116:19993:15999`.

**Comment by SteveMarshallFSP** [comment] 2020-02-17 04:11
Hi Daniel

Thanks for your quick reply... the zip file appears to be corrupt so I was able to extract the read you listed above 
[extract_reads.sam.gz](https://github.com/PapenfussLab/gridss/files/4211763/extract_reads.sam.gz)

Cheers
Steve

**Comment by d-cameron** [comment] 2020-02-18 02:50
I'm not able to reproduce locally as I can't seem to find the "Tg" contig
you have in your reference genome.

The zip file contains the minimal information required for reproduction of
the error. Specifically, this is:

   - *.sv.bam: reads in the assembly graph at the time of error (ususally <
   100)
   - *metric*: metrics files for the input files (used to
   determine expected insert size distribution, and empirical weighting of
   reads)
   - masked_ref.fa: reference genome with regions not near any of the
   assembly reads N masked (this makes a 3Gb reference compress down to a few
   tens of kb)
   - configuration file (if used)

If those files exist (they're deleted once the zip is created), could you
create a new zip and send it through? Failing that, could you send me
through your corrupted zip? I might be able to recover the ref genome out
of it and reproduce locally.

**Comment by SteveMarshallFSP** [comment] 2020-02-18 03:37
Can we correspond via email?

**Comment by SteveMarshallFSP** [comment] 2020-02-18 04:06
I'm also wondering maybe the approach I'm using isn't correct. Essentially looking for insertion of custom dna into the human genome (expect that these will insert in highly repetitive regions). I created a human + custom sequence database. Aligned my reads using bwa mem to this custom db and then used gridss... Does this make sense?

**Comment by d-cameron** [comment] 2020-03-04 04:49
Sorry for the delay. Email is fine for data transfer of the `gridss_minimal_reproduction_data_for_error_0.zip` (cameron.d  [wehi.edu.au](http://wehi.edu.au))

The approach of augmented reference genome is indeed the way to go but if your custom DNA insert is novel with respect to the human reference genome. If your construct contains sequence identical or with high similarity to the human genome, then reads aligning to your transgene with be multimapping (mapq<10) and ignored.


>expect that these will insert in highly repetitive regions

Inserts into repetative regions of the human genome will be reported by GRIDSS as single breakends on the Tg contig. GRIDSS will report the breakpoint sequence, but if it can't uniquely place it (e.g. insertion into a centromere), then it won't call a breakpoint.

Generally speaking, the transgene insertion location identification workflow I use goes something like:
- Add transgene to host reference
- N mask regions of homology to transgene (e.g. mask out mouse MYC if inserting human MYC into a mouse)
- Run GRIDSS
- Manually look at breakpoints and single breakends on the transgene contig
  - ignore SVs to mask flanking regions (e.g. you expect SVs to the region flanking the portion of mouse MYC that your masked)
  - Check for breakpoints anywhere in the transgene, not just at the bounds
- Look for chaining SVs around the putative insertion sites (insertions are not necessarily clean)
- Complain that the sequence that your collaborator gave you wasn't actually the construct they made (e.g. they included a PhiX but didn't tell you; they gave your the full human gene sequence but inserted the processed transcript so you have SVs at each exon; ...)

**Comment by d-cameron** [comment] 2020-03-13 00:40
Should be fixed in 2.8.1. Please reopen if this is not the case.

**Closed by d-cameron** 2020-03-13 00:40 UTC
