### ISSUE TITLE
Can not find reference genome index

### ISSUE THREAD

**Issue by YULEITSINGTAO** [PapenfussLab/gridss#481] opened 2021-04-02 17:32 UTC
Hello there, 

When I tried to use hg19.fa to call the SV, gridss show an error saying: Reference genome does not have an index. However, I do have a hg19.fa.fai file in the same directory as the hg19.fa file. I do not know why gridss can not find the hg19.fa.fai file. 

I appreciate your time and help in advance.

Thanks
Lei

**Comment by d-cameron** [comment] 2021-04-03 12:32
Please attach the log file output from gridss.

Gridss should automatically create the required index files if they are
missing. At this point it is unclear what the error and root cause are. The
log files are extremely helpful in resolving errors.

**Comment by YULEITSINGTAO** [comment] 2021-04-04 02:48
Hello there,

Thanks for replying. I attached the log file.

Thanks
Lei

**Comment by YULEITSINGTAO** [comment] 2021-04-04 02:50
Hello there,

Thanks for replying. The log file showing:

Thu Apr  1 20:42:09 PDT 2021: Full log file is:
./gridss.full.20210401_204209.pelican.55042.log
Thu Apr  1 20:42:09 PDT 2021: Not found /usr/bin/time
Thu Apr  1 20:42:09 PDT 2021: Using GRIDSS jar
gridss-2.11.0-gridss-jar-with-dependencies.jar
Thu Apr  1 20:42:09 PDT 2021: Using reference genome "reference/hg19.fa"
Thu Apr  1 20:42:09 PDT 2021: Using output VCF output/test.output.vcf.gz
Thu Apr  1 20:42:09 PDT 2021: Using 8 worker threads.
Thu Apr  1 20:42:09 PDT 2021: Using no blacklist bed. The encode DAC
blacklist is recommended for hg19.
Thu Apr  1 20:42:09 PDT 2021: Using JVM maximum heap size of 30g for
assembly and variant calling.
Thu Apr  1 20:42:09 PDT 2021: Using input file
/rhome/lyu062/shared/coh/mark_duplicate_bam/WGS_M02N.sort.deduplicated.bam
Thu Apr  1 20:42:09 PDT 2021: Using input file
/rhome/lyu062/shared/coh/mark_duplicate_bam/WGS_M02T.sort.deduplicated.bam
Thu Apr  1 20:42:09 PDT 2021: Found
/opt/linux/centos/7.x/x86_64/pkgs/R/4.0.1/bin/Rscript
Thu Apr  1 20:42:09 PDT 2021: Found
/opt/linux/centos/7.x/x86_64/pkgs/samtools/1.11/bin/samtools
Thu Apr  1 20:42:09 PDT 2021: Found
/opt/linux/centos/7.x/x86_64/pkgs/java/jdk1.8.0_45/bin/java
Thu Apr  1 20:42:09 PDT 2021: Found
/opt/linux/centos/7.x/x86_64/pkgs/bwa/0.7.17/bwa
Thu Apr  1 20:42:09 PDT 2021: samtools version: 1.11+htslib-1.11
Thu Apr  1 20:42:09 PDT 2021: R version: R scripting front-end version
4.0.1 (2020-06-06)
Thu Apr  1 20:42:09 PDT 2021: bwa Version: 0.7.17-r1188
Thu Apr  1 20:42:10 PDT 2021: bash version: GNU bash, version
4.2.46(2)-release (x86_64-redhat-linux-gnu)
Thu Apr  1 20:42:10 PDT 2021: java version: java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14) Java HotSpot(TM)
64-Bit Server VM (build 25.45-b02, mixed mode)
Thu Apr  1 20:42:11 PDT 2021: Max file handles: 4096
Thu Apr  1 20:42:11 PDT 2021: Running GRIDSS steps: call,
Thu Apr  1 20:42:11 PDT 2021: Skipping pre-processing.
Thu Apr  1 20:42:11 PDT 2021: Skipping assembly assembly_test.bam
Thu Apr  1 20:42:11 PDT 2021: Start calling output/test.output.vcf.gz
Thu Apr  1 20:42:11 PDT 2021: Running IdentifyVariants
output/test.output.vcf.gz
INFO 2021-04-01 20:42:12 Defaults Found file for property
samjdk.reference_fasta:
/bigdata/jialab/shared/coh_SV/GRIDSS/reference/hg19.fa
INFO 2021-04-01 20:42:12 IdentifyVariants

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
**********
https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    IdentifyVariants -TMP_DIR . -WORKING_DIR .
-REFERENCE_SEQUENCE reference/hg19.fa -WORKER_THREADS 8 -INPUT
/rhome/lyu062/shared/coh/mark_duplicate_bam/WGS_M02N.sort.deduplicated.bam
-INPUT
/rhome/lyu062/shared/coh/mark_duplicate_bam/WGS_M02T.sort.deduplicated.bam
-ASSEMBLY assembly_test.bam -OUTPUT_VCF
./test.output.vcf.gz.gridss.working/test.output.vcf.gz.unallocated.vcf
-READ_PAIR_CONCORDANT_PERCENT 0.995
**********


20:42:14.758 INFO  NativeLibraryLoader - Loading libgkl_compression.so from
jar:file:/bigdata/jialab/shared/coh_SV/GRIDSS/gridss-2.11.0-gridss-jar-with-dependencies.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Apr 01 20:42:14 PDT 2021] IdentifyVariants
OUTPUT_VCF=./test.output.vcf.gz.gridss.working/test.output.vcf.gz.unallocated.vcf
ASSEMBLY=[assembly_test.bam]
INPUT=[/rhome/lyu062/shared/coh/mark_duplicate_bam/WGS_M02N.sort.deduplicated.bam,
/rhome/lyu062/shared/coh/mark_duplicate_bam/WGS_M02T.sort.deduplicated.bam]
READ_PAIR_CONCORDANT_PERCENT=0.995 WORKER_THREADS=8 WORKING_DIR=.
TMP_DIR=[.] REFERENCE_SEQUENCE=reference/hg19.fa    IGNORE_DUPLICATES=true
VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5
MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false
USE_JDK_INFLATER=false
[Thu Apr 01 20:42:14 PDT 2021] Executing as ***@***.*** on Linux
3.10.0-1160.15.2.el7.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM
1.8.0_45-b14; Deflater: Intel; Inflater: Intel; Provider GCS is not
available; Picard version: 2.11.0-gridss
INFO 2021-04-01 20:42:15 GridssConfiguration maxCoverage=25000
INFO 2021-04-01 20:42:15 GridssConfiguration minMapq=20
INFO 2021-04-01 20:42:15 GridssConfiguration fallbackMapq=20
INFO 2021-04-01 20:42:15 GridssConfiguration fallbackBaseq=20
INFO 2021-04-01 20:42:15 GridssConfiguration minAnchorShannonEntropy=0.5
INFO 2021-04-01 20:42:15 GridssConfiguration dovetailMargin=4
INFO 2021-04-01 20:42:15 GridssConfiguration softclip.minAverageQual=5.0
INFO 2021-04-01 20:42:15 GridssConfiguration softclip.minLength=5
INFO 2021-04-01 20:42:15 GridssConfiguration softclip.minAnchorIdentity=0.95
INFO 2021-04-01 20:42:15 GridssConfiguration
softclip.realignSplitReads=false
INFO 2021-04-01 20:42:15 GridssConfiguration
useReadGroupSampleNameCategoryLabel=true
INFO 2021-04-01 20:42:15 GridssConfiguration chunkSize=10000000
INFO 2021-04-01 20:42:15 GridssConfiguration
chunkSequenceChangePenalty=250000
INFO 2021-04-01 20:42:15 GridssConfiguration hashEvidenceID=true
INFO 2021-04-01 20:42:15 GridssConfiguration adapter=AGATCGGAAGAG
INFO 2021-04-01 20:42:15 GridssConfiguration adapter=ATGGAATTCTCG
INFO 2021-04-01 20:42:15 GridssConfiguration adapter=CTGTCTCTTATA
INFO 2021-04-01 20:42:15 GridssConfiguration
scoring.model=FastEmpiricalReferenceLikelihood
INFO 2021-04-01 20:42:15 GridssConfiguration assembly.k=25
INFO 2021-04-01 20:42:15 GridssConfiguration assembly.minReads=3
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.includePairAnchors=true
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.pairAnchorMismatchIgnoreEndBases=5
INFO 2021-04-01 20:42:15 GridssConfiguration assembly.writeFiltered=false
INFO 2021-04-01 20:42:15 GridssConfiguration assembly.anchorLength=300
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.removeMisassembledPartialContigsDuringAssembly=true
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.maxExpectedBreakendLengthMultiple=1.5
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.errorCorrection.kmerErrorCorrectionMultiple=10.0
INFO 2021-04-01 20:42:15 GridssConfiguration assembly.errorCorrection.k=21
INFO 2021-04-01 20:42:15 GridssConfiguration assembly.realignContigs=true
INFO 2021-04-01 20:42:15 GridssConfiguration assembly.recoverAfterError=true
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.downsample.acceptDensityPortion=0.1
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.downsample.targetEvidenceDensity=1
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.downsample.minimumDensityWindowSize=1000
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.downsample.densityDownsampleRateClippedReads=0.9
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.downsample.densityDownsampleRateDiscordantReads=0.75
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.positional.maxPathLengthMultiple=1.1
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.positional.retainWidthMultiple=2.0
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.positional.flushWidthMultiple=1.0
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.positional.maximumNodeDensity=2.0
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.positional.trimSelfIntersectingReads=true
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.positional.forceFullMemoizationRecalculationAt=0.8
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.positional.safetyModePathCountThreshold=50000
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.positional.safetyModeContigsToCall=3
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.contigNamePrefix=asm%d-
INFO 2021-04-01 20:42:15 GridssConfiguration
assembly.longReadReadLengthThreshold=1000
INFO 2021-04-01 20:42:15 GridssConfiguration variantcalling.minReads=2
INFO 2021-04-01 20:42:15 GridssConfiguration variantcalling.minScore=50.0
INFO 2021-04-01 20:42:15 GridssConfiguration variantcalling.minSize=10
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.callUnassembledBreakpoints=true
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.callUnassembledBreakends=false
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.callFullyAnchoredAssemblyVariants=false
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.breakendMargin=10
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.writeFiltered=false
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.simplecalls=false
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.maxBreakendHomologyLength=300
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.breakendHomologyAlignmentMargin=10
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.requireAssemblyCategorySupport=true
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.callBreakends=true
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.includeSupportingReadNames=false
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.breakpointLowQuality=500.0
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.breakendLowQuality=1500.0
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.breakendMaxAssemblySupportBias=0.5
INFO 2021-04-01 20:42:15 GridssConfiguration
variantcalling.ignoreMissingAssemblyFile=false
INFO 2021-04-01 20:42:15 GridssConfiguration terminateOnFirstError=true
INFO 2021-04-01 20:42:15 GridssConfiguration
visualisation.directory=visualisation
INFO 2021-04-01 20:42:15 GridssConfiguration visualisation.buffers=false
INFO 2021-04-01 20:42:15 GridssConfiguration
visualisation.bufferTrackingItervalInSeconds=60
INFO 2021-04-01 20:42:15 GridssConfiguration visualisation.timeouts=false
INFO 2021-04-01 20:42:15 GridssConfiguration
visualisation.evidenceAllocation=false
INFO 2021-04-01 20:42:15 GridssConfiguration
visualisation.assemblyProgress=false
INFO 2021-04-01 20:42:15 GridssConfiguration
visualisation.assemblyTelemetry=false
INFO 2021-04-01 20:42:15 GridssConfiguration
visualisation.maxCliqueTelemetry=false
INFO 2021-04-01 20:42:15 GridssConfiguration
visualisation.assemblyGraph=false
INFO 2021-04-01 20:42:15 GridssConfiguration
visualisation.assemblyGraphFullSize=false
INFO 2021-04-01 20:42:15 GridssConfiguration
visualisation.assemblyContigMemoization=false
[Thu Apr 01 20:42:15 PDT 2021] gridss.IdentifyVariants done. Elapsed time:
0.02 minutes.
Runtime.totalMemory()=1009254400
Exception in thread "main" java.lang.IllegalArgumentException: Reference
genome does not have an index. Create using `samtools faidx`.
at
au.edu.wehi.idsv.picard.TwoBitBufferedReferenceSequenceFile.<init>(TwoBitBufferedReferenceSequenceFile.java:34)
at
au.edu.wehi.idsv.GenomicProcessingContext.LoadSynchronizedReference(GenomicProcessingContext.java:104)
at
au.edu.wehi.idsv.GenomicProcessingContext.<init>(GenomicProcessingContext.java:61)
at au.edu.wehi.idsv.ProcessingContext.<init>(ProcessingContext.java:40)
at
gridss.cmdline.MultipleSamFileCommandLineProgram.getContext(MultipleSamFileCommandLineProgram.java:193)
at
gridss.cmdline.MultipleSamFileCommandLineProgram.doWork(MultipleSamFileCommandLineProgram.java:153)
at
picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
at gridss.IdentifyVariants.main(IdentifyVariants.java:26)

**Comment by d-cameron** [comment] 2021-04-04 23:23
> Thu Apr  1 20:42:09 PDT 2021: Full log file is: ./gridss.full.20210401_204209.pelican.55042.log

Can you attach the full log file?

> Thu Apr  1 20:42:11 PDT 2021: Running GRIDSS steps: call,

It looks like you specified `--steps call ` on the command line without actually running all the steps required to be run before the `call` step. `--steps` is only useful if splitting GRIDSS up into multiple jobs when running on a cluster. For most users, this parameter should not be used.

**Comment by YULEITSINGTAO** [comment] 2021-04-05 05:10
Hello, 
I deleted the steps parameter and the log showing the error: 

Reference genome used by /rhome/lyu062/shared/shared/coh/WGS_M02N.sort.bam does not match reference genome ref/hg19.fa

I attached the full error log 
[gridss.full.20210404_220421.pelican.57486.log](https://github.com/PapenfussLab/gridss/files/6256422/gridss.full.20210404_220421.pelican.57486.log)

And the commend I used is:
--------------------------------------------------------------------------------------------------------------------
#!/bin/bash -l
module load samtools
module load bwa

reference="ref/hg19.fa"
Normal="/rhome/lyu062/shared/shared/coh/WGS_M02N.sort.bam"
Tumor="/rhome/lyu062/shared/shared/coh/WGS_M02T.sort.bam"


./gridss.sh --reference $reference \
 --output output/test.output.vcf.gz \
 --assembly assembly_test.bam \
 --jar gridss-2.11.0-gridss-jar-with-dependencies.jar \
 $Normal $Tumor

Thanks
Lei

**Comment by YULEITSINGTAO** [comment] 2021-04-05 05:16
Hello, 

I deleted the "steps" parameter and GRIDSS could finish the PrepareReference step but it return a new error:

ERROR	2021-04-04 22:04:28	ReferenceCommandLineProgram	Reference genome used by /rhome/lyu062/shared/shared/coh/WGS_M02N.sort.bam does not match reference genome ref/hg19.fa. The reference supplied must match the reference used for every input.

I attach the full error log file: 
[gridss.full.20210404_220421.pelican.57486.log](https://github.com/PapenfussLab/gridss/files/6256438/gridss.full.20210404_220421.pelican.57486.log)

For more information, the command I used to run GRIDSS is:
----------------------------------------------------------------------
module load samtools
module load bwa

reference="ref/hg19.fa"
Normal="/rhome/lyu062/shared/shared/coh/WGS_M02N.sort.bam"
Tumor="/rhome/lyu062/shared/shared/coh/WGS_M02T.sort.bam"


./gridss.sh --reference $reference \
 --output output/test.output.vcf.gz \
 --assembly assembly_test.bam \
 --jar gridss-2.11.0-gridss-jar-with-dependencies.jar \
 $Normal $Tumor


Thanks
Lei

**Comment by d-cameron** [comment] 2021-04-05 22:34
You aligned your bams to a different version of hg19. The reference supplied to GRIDSS must  be exactly the same reference that you used for alignment.

**Closed** 2021-04-13 05:27 UTC

**Comment by YULEITSINGTAO** [comment] 2021-04-15 23:34
Thanks for your help!
