### ISSUE TITLE
IdsvSamFileMetrics	thinks that my reads are single-end

### ISSUE THREAD

**Issue by iprada** [PapenfussLab/gridss#72] opened 2017-04-12 14:19 UTC
Hi! I am running gridss in a simulated paired-end dataset. When I run it everything works fine, and the output files of gridss look fine. However, gridss raised this mesage:

`INFO	2017-04-12 16:11:16	IdsvSamFileMetrics	No pair-end insert size metrics found in ./sorted_paired_end_sim_aln.gridss.assembly.bam.gridss.working/sorted_paired_end_sim_aln.gridss.assembly.bam.insert_size_metrics. Assuming this library contains single-end reads`

I'm not sure why is this happening, and if it is something we should be aware of.

Thank you very much

**Comment by d-cameron** [comment] 2017-04-12 22:07
It's referring to the break-end assemblies produced from your reads. These are indeed unpaired but the warning message is unnecessary. I'll look at removing it.

**Comment by d-cameron** [comment] 2017-04-12 22:08
Possibly duplicate of #47

**Comment by d-cameron** [comment] 2017-04-13 05:46
The fix will be included in the next release. Thanks for your report.

**Closed by d-cameron** 2017-04-13 05:46 UTC

**Comment by iprada** [comment] 2017-04-13 10:24
thank's!
