### ISSUE TITLE
Positional Assembler... 

### ISSUE THREAD

**Issue by CapitanFlint** [PapenfussLab/gridss#244] opened 2019-09-09 23:09 UTC
I'd seen this problem across the forum, but still there is no answer. I will post the very first lines of the error (it is very long), so maybe it can contribute to the solution.

ERROR	2019-09-09 19:05:37	PositionalAssembler	Error assembling 000760F|quiver. This should not happen. Please raise an issue at https://github.com/PapenfussLab/gridss/issues. Attempting recovery by resuming assembly at 000762F|quiver:438
java.lang.AssertionError
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.removeFromGraph(NonReferenceContigAssembler.java:647)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushReferenceNodes(NonReferenceContigAssembler.java:282)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:233)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:169)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:69)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:109)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:85)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:55)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:220)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:178)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$1(AssemblyEvidenceSource.java:87)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
ERROR	2019-09-09 19:05:37	PositionalAssembler	Error assembling 000619F|quiver. This should not happen. Please raise an issue at https://github.com/PapenfussLab/gridss/issues. Attempting recovery by resuming assembly at 000620F|quiver:221

Then i got like thousends of those errors with different PositionalAssembler NUMBER|quiver

If anyone know how to solve this please don't be shy.

Thank you,

Bruno

**Comment by d-cameron** [comment] 2019-09-10 13:05
>I'd seen this problem across the forum, but still there is no answer.

This issue remains open as nobody has so far be able to provide a minimal BAM that reproduces the problem. I can reproduce it myself but only after multiple hours of runtime and when I subset the offending BAM the error goes away (likely due to the offsets of read batch loading being different).

>`Attempting recovery by resuming assembly at 000762F|quiver:438`

Are you able to provide a minimal (e.g. 000762F|quiver:1-1000) BAM that reproduces the error? 438bp into a contig is the best candidate I've seen for an example that debugging would be viable to do.

>Then i got like thousends of those errors with different PositionalAssembler NUMBER|quiver
That is definitely unusual. First, some sanity checking:

- are you read names actually unique?
- are you SAM tags correct?
- is your data single-end or paired-end short read sequencing data?

**Comment by CapitanFlint** [comment] 2019-09-10 16:03
Cheking sanity, i used Bamutil with this commands:

bam validate --in "bam_file" --verbose --refFile "fasta_reference"


And then i got this:

Record 75
INVALID_TAG (WARNING) : Incorrect MD Tag, 112A0A0C0A1G0A6, should be 112AACA1GA6.

Record 86
INVALID_TAG (WARNING) : Incorrect MD Tag, 0A119, should be A119.

Record 110
INVALID_TAG (WARNING) : Incorrect MD Tag, 86C0C16C5, should be 86CC16C5.

Record 138
INVALID_TAG (WARNING) : Incorrect MD Tag, 12A25^AATTTAA5G0C1A19A17G24G15, should be 12A25^AATTTAA5GC1A19A17G24G15.

Record 141
INVALID_TAG (WARNING) : Incorrect MD Tag, 0G47A17G1A3G18G33, should be G47A17G1A3G18G33.

Record 154
INVALID_TAG (WARNING) : Incorrect MD Tag, 47C29T6A0G3C28C4, should be 47C29T6AG3C28C4.

Record 161
INVALID_TAG (WARNING) : Incorrect MD Tag, 15T6A0G3C81C5A9, should be 15T6AG3C81C5A9.

Record 164
INVALID_TAG (WARNING) : Incorrect MD Tag, 0G125, should be G125.

Record 166
INVALID_TAG (WARNING) : Incorrect MD Tag, 24A0T40C5A37, should be 24AT40C5A37.

Record 169
INVALID_TAG (WARNING) : Incorrect MD Tag, 0T29T26G39C28, should be T29T26G39C28.

Record 206
INVALID_TAG (WARNING) : Incorrect MD Tag, 28A0C45G25T8C3, should be 28AC45G25T8C3.

Record 255
INVALID_TAG (WARNING) : Incorrect MD Tag, 0T1C0T0T34G1T0A5A1C2T4A2T3T2T1C3C0T0G0G0G0C1G0A0C0A0A0T0A4T0G0G0C0T0C0A0C0G1T23, should be T1CTT34G1TA5A1C2T4A2T3T2T1C3CTGGGC1GACAATA4TGGCTCACG1T23.

Record 274
INVALID_TAG (WARNING) : Incorrect MD Tag, 0C60G41G21, should be C60G41G21.

Record 275
INVALID_TAG (WARNING) : Incorrect MD Tag, 0C60G41G22, should be C60G41G22.

Record 331
INVALID_TAG (WARNING) : Incorrect MD Tag, 10T33T21C1A23T20T0T8A2, should be 10T33T21C1A23T20TT8A2.

Record 390
INVALID_TAG (WARNING) : Incorrect MD Tag, 33C0A2T87, should be 33CA2T87.

Record 391
INVALID_TAG (WARNING) : Incorrect MD Tag, 24C0A2T97, should be 24CA2T97.

Record 485
INVALID_TAG (WARNING) : Incorrect MD Tag, 6T0G118, should be 6TG118.

Record 488
INVALID_TAG (WARNING) : Incorrect MD Tag, 17T56T10G0T38, should be 17T56T10GT38.

Record 544
INVALID_TAG (WARNING) : Incorrect MD Tag, 6G20C0A1G76, should be 6G20CA1G76.

Record 587
INVALID_TAG (WARNING) : Incorrect MD Tag, 0T10^T5A50A28A1A26, should be T10^T5A50A28A1A26.

Record 599
INVALID_TAG (WARNING) : Incorrect MD Tag, 32A28A31A1G0T6T15C4, should be 32A28A31A1GT6T15C4.

Record 601
INVALID_TAG (WARNING) : Incorrect MD Tag, 9A28A31A1G0T6T15C14A9, should be 9A28A31A1GT6T15C14A9.

Record 720
INVALID_TAG (WARNING) : Incorrect MD Tag, 10G0G0T0A77C34, should be 10GGTA77C34.

Record 738
INVALID_TAG (WARNING) : Incorrect MD Tag, 0C11T0C4A8A0C3A24, should be C11TC4A8AC3A24.

Record 739
INVALID_TAG (WARNING) : Incorrect MD Tag, 11T0C4A8A0C3A24, should be 11TC4A8AC3A24.


And so on and so on.....


Do you think this could be the problem?
I want to exhaust all the possibilities before providing to you the minimal BAM file.

Thank you in advance,

Bruno

**Comment by d-cameron** [comment] 2019-09-11 02:55
GRIDSS doesn't use the MD tag so that's not the problem. I've traced this
particular error message back to duplicate read names in the input file for
other users so it's definitely worth checking that.

**Comment by d-cameron** [comment] 2019-09-27 01:41
Should be resolved in 2.6.2

**Closed by d-cameron** 2019-09-27 01:41 UTC
