### ISSUE TITLE
A lot of warnings and errors

### ISSUE THREAD

**Issue by ptranvan** [PapenfussLab/gridss#314] opened 2020-03-28 11:00 UTC
Hi,

I tried to make a test run with version 2.8.1 but got quite a lot of warnings and errors:

```
Sat Mar 28 11:41:22 CET 2020    Complete calling        sample.vcf.gz
Sat Mar 28 11:41:22 CET 2020    Run complete with 220 warnings and 112 errors.
```

Looking at the log file, these are the kind of errors:

```
ERROR   2020-03-28 11:32:10     NonReferenceContigAssembler     Sanity check failure: found path with no support (Scaffold03:1903564)
WARNING 2020-03-28 11:32:10     PositionalAssembler     Error during assembly of chromosome Scaffold03 (289 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.RuntimeException: Sanity check failure: found path with no support (Scaffold03:1903564)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:646)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:224)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:254)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:188)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:81)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:241)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:108)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:66)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:198)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

How to fix this ?

**Comment by d-cameron** [comment] 2020-04-02 02:15
Should be fixed in the latest release (v2.8.2).

**Closed by d-cameron** 2020-04-02 02:15 UTC

**Comment by lindenb** [comment] 2020-05-12 13:24
I've got the same warnings with **v2.9.1**

```
INFO	2020-05-12 13:16:33	NonReferenceContigAssembler	Sanity check failure: non-empty graph with no contigs called hs37d5
INFO	2020-05-12 13:16:33	PositionalAssembler	Error during assembly of chromosome hs37d5 (0 reads in graph). Attempting recovery by
 rebuilding assembly graph.
java.lang.RuntimeException: Sanity check failure: non-empty graph with no contigs called hs37d5
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:279)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:195)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:76)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:234)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:103)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:61)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:238)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:196)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
```

**Comment by d-cameron** [comment] 2020-05-13 01:57
Did it generate a GRIDSS gridss_minimal_reproduction_data_for_error_1.zip file? If not, then the assembly recovery was successful and the issue was corrected before it affected assembly output (hence the downgrade from WARNING to INFO).

There's still a bug in the assembly streaming, but it's a difficult to reproduce edge case that requires streaming possibly megabase long regions to get the internal data structures to the point where it actually hits the error. If you ever find a sample where a `gridss_minimal_reproduction_data_for_error` file is output, please post that as it means I'll be able to reproduce locally with a data set small enough to actually determine where the error occurs and finally fix it.

**Comment by rosehuang24** [comment] 2020-08-13 06:27
Hi, I too encounter the warning message with v2.9.4 and a `gridss_minimal_reproduction_data_for_error` file was generated for each of the input, but there is an output vcf although it seems to be rather incomplete. My code is: 
```
$gridss --threads 8 -j $gridssjar --reference $ref_genome --output $OUTDIR/output_file \
--assembly Clean_01 --assembly Clean_02 \
--repeatmaskerbed $repeatmasker \
$midfileDIR/recaled_Clean_01.bam $midfileDIR/recaled_Clean_02.bam 
```

And the error message: 

```
ERROR   2020-08-11 14:53:18     SupportNodeIterator     Error: kmer in evidence bJJ15rTUyaBr0XdJVckYaa-xN0pc7zY8 of read A00153:514:HWNYJDSXX:2:2330:24975:12524 (33:6783017 97S21M1D7M2D13M2D12M) out of bounds. Kmer support starts at 6782368 which is more than 633 before the breakpoint start position at <(34):6783009(6783002-6783017) (34):6783008(6783001-6783016)>
INFO    2020-08-11 14:53:19     NonReferenceContigAssembler     Sanity check failure: found path with no support (33:6782474)
INFO    2020-08-11 14:53:19     PositionalAssembler     Error during assembly of chromosome 33 (1876 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.RuntimeException: Sanity check failure: found path with no support (33:6782474)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:666)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:231)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:261)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:195)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:76)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:245)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:103)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:61)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:198)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
INFO    2020-08-11 14:53:19     PositionalAssembler     java.lang.RuntimeException: Sanity check failure: found path with no support (33:6782474)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:666)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:231)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:261)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:195)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:76)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:245)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:103)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:61)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:198)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Your help and time is appreciated!
Rose

**Comment by rosehuang24** [comment] 2020-08-13 06:33
Hi,

I too encounter the error message when using v2.9.4, and the `gridss_minimal_reproduction_data_for_error` zip file is generated for each of the input. There is a result vcf but it seems to be rather incomplete. Here is my code: 
```
$gridss --threads 8 -j $gridssjar --reference $ref_genome --output $outputfile \
--assembly Clean_01 --assembly Clean_02 \
--repeatmaskerbed $repeatmasker \
$midfileDIR/recaled_Clean_01.bam $midfileDIR/recaled_Clean_02.bam
```
and this is the error message example:
```
ERROR   2020-08-11 14:53:18     SupportNodeIterator     Error: kmer in evidence bJJ15rTUyaBr0XdJVckYaa-xN0pc7zY8 of read A00153:514:HWNYJDSXX:2:2330:24975:12524 (33:6783017 97S21M1D7M2D13M2D12M) out of bounds. Kmer support starts at 6782368 which is more than 633 before the breakpoint start position at <(34):6783009(6783002-6783017) (34):6783008(6783001-6783016)>
INFO    2020-08-11 14:53:19     NonReferenceContigAssembler     Sanity check failure: found path with no support (33:6782474)
INFO    2020-08-11 14:53:19     PositionalAssembler     Error during assembly of chromosome 33 (1876 reads in graph). Attempting recovery by rebuilding assembly graph.
java.lang.RuntimeException: Sanity check failure: found path with no support (33:6782474)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:666)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:231)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:261)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:195)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:76)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:245)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:103)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:61)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:198)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
INFO    2020-08-11 14:53:19     PositionalAssembler     java.lang.RuntimeException: Sanity check failure: found path with no support (33:6782474)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:666)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:231)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:261)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:195)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:76)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:245)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:103)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:61)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:198)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Your time and help is greatly appreciated!
Rose

**Comment by d-cameron** [comment] 2020-08-13 12:09
Can you send through to me, or attach to this issue, the `gridss_minimal_reproduction_data_for_error_0.zip` file that was generated?

**Comment by rosehuang24** [comment] 2020-08-14 02:29
Hi,
Here is the file

[gridss_minimal_reproduction_data_for_error_1.zip](https://github.com/PapenfussLab/gridss/files/5072390/gridss_minimal_reproduction_data_for_error_1.zip)

Thank you
Rose

**Comment by rosehuang24** [comment] 2020-08-18 02:23
Hi,

I changed my input bam and there is no more error file produced. For anyone who have the same problem, I used to put recalibrated bam file from GATK pipeline, but once I change it to only duplicated-removed bam it seems to work fine. 

Thanks again!
Rose
