### ISSUE TITLE
AssemblyEvidenceSource Category Number Mismatch Error

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#406] opened 2020-09-23 13:00 UTC
I am doing the three stages separately. It has worked smoothly in the past. When I run the calling stage, I get an error about the number of categories mismatching.

```
Wed Sep 23 16:30:06 AEST 2020: Skipping assembly        /scratch/hm82/OSCC//assembled/PONassembly.bam
Wed Sep 23 16:30:06 AEST 2020: Start calling    /scratch/hm82/OSCC//structuralVariants/HeadNeckAllHealthy.vcf.gz
Wed Sep 23 16:30:06 AEST 2020: Running  IdentifyVariants        /scratch/hm82/OSCC//structuralVariants/HeadNeckAllHealthy.vcf.gz
   ...           ...
ERROR   2020-09-23 16:30:14     AssemblyEvidenceSource  Fatal error: GRIDSS assembly does not have the expected number of input categories (found 1, expected 10). GRIDSS performs joint assembly and does not support per-input assembly. Make sure the same input and labels are specified in the same order for the assembly and variant calling steps.
```

But, there are indeed 10 categories in the resulting file of the second stage, the assemble stage.

```
@PG     ID:gridss0      PN:gridss       VN:2.9.4-gridss
@PG     ID:samtools     PN:samtools     PP:gridss0      VN:1.10 CL:samtools view -H /scratch/hm82/OSCC/assembled/PONassembly.bam
@CO     gridss_input_category=Oral_1-N
@CO     gridss_input_category=Oral_2-N
@CO     gridss_input_category=Oral_3-N
@CO     gridss_input_category=Oral_4-N
@CO     gridss_input_category=Oral_5-N
@CO     gridss_input_category=Oral_6-N
@CO     gridss_input_category=Oral_7-N
@CO     gridss_input_category=Oral_8-N
@CO     gridss_input_category=Oral_9-N
@CO     gridss_input_category=Oral_10-N
```

What could be triggering this error?

**Comment by d-cameron** [comment] 2020-10-02 05:37
Duplicate of #354 (see this issue for the workaround)/#403

Actioning as #397

**Closed by d-cameron** 2020-10-02 05:37 UTC
Labels: duplicate

**Comment by d-cameron** [comment] 2020-10-02 05:38
>It has worked smoothly in the past.

If you were running a version of GRIDSS before I put this sanity check in, then it would have silently misattributed assembly support to the wrong sample.
