### ISSUE TITLE
gridss failure with exit code 6

### ISSUE THREAD

**Issue by kostasgalexiou** [PapenfussLab/gridss#323] opened 2020-04-11 22:57 UTC
Hi,

I am trying to run gridss but I am getting an error that I cannot understand its meaning. I am attaching the 2 log files generated during the run; "full" log and "timing" log:

[gridss.full.20200411_171619.wright.20980.log](https://github.com/PapenfussLab/gridss/files/4465608/gridss.full.20200411_171619.wright.20980.log)
[gridss.timing.20200411_171619.wright.20980.log](https://github.com/PapenfussLab/gridss/files/4465609/gridss.timing.20200411_171619.wright.20980.log)

Below is the command that I am running (6 CPUs, 12G per CPU), in order to obtain SVs for 2 samples; EG2 and Texas:

`home/kalexiou/local/software/gridss/scripts/gridss.sh --reference /projects/061-SECUENCIAS-Pd_Pp/Reference/Peach_V2_release/genome/v2.1_gdr/Prunus_persica_main_genome_scaffolds.fasta --output gridss/EG2-Texas.vcf.gz --threads 6 --workingdir gridss --steps All --maxcoverage 1000 --jar /home/kalexiou/local/software/gridss/gridss-2.8.3-gridss-jar-with-dependencies.jar --assembly gridss/EG2-Texas_assembly.bam EG2.sort.bam Texas_1_trimmed.sort.pcr_rem.RG.SV.bam`

Any help will be greatly appreciated.

Thanks in advance,
Kostas

**Comment by d-cameron** [comment] 2020-04-13 01:52
The error message indicates a failure in a C++ program. The most likely cause is that your `R` installation is broken.

**Comment by kostasgalexiou** [comment] 2020-04-13 18:51
Hi,

Thanks for your reply. 

That's strange. I am launching the command in my company's cluster and loading R/3.5.3 for usage. I've never got any problems when using R in the work cluster.

Regards
Kostas

**Comment by d-cameron** [comment] 2020-04-27 05:19
Is this issue still outstanding? Have you checked your samtools installation is also working?

**Comment by kostasgalexiou** [comment] 2020-04-28 09:46
Samtools is fully functional. I have just tried launching the same command and still getting the same error

**Comment by d-cameron** [comment] 2020-04-28 12:41
The error is definitely not in the GRIDSS code itself which makes this really hard to debug. Are you able to do any of the following to assist in tracing the root cause of this issue:

- Rerun with a different JVM version (e.g java 8 or java 11)
- Run the picard tools `CollectInsertSizeMetrics` on `EG2.sort.bam` to check that it runs successfully in your environment.
- Edit gridss.sh and add `-Dsnappy.disable=true -Dsamjdk.try_use_intel_deflater=false` to the `$jvm_args` variable. Rerun gridss with the new settings
- Run gdb on the failing java invocation and post the stack trace
  - This will enable us to identify if it's a JVM issue, or an issue with one of the native libraries included in htsjdk (e.g. snappy, or GKL).

**Comment by d-cameron** [comment] 2020-04-28 23:45
picard tools can be run using `java -cp  /home/kalexiou/local/software/gridss/gridss-2.8.3-gridss-jar-with-dependencies.jar  picard.cmdline.PicardCommandLine CollectInsertSizeMetrics I=EG2.sort.bam O=eg2test_metrics`

**Comment by kostasgalexiou** [comment] 2020-04-30 13:43
Hi d-cameron,

Of the 4 points that you are suggesting:

1. ` java -version` 
`java version "1.8.0_144"`
`Java(TM) SE Runtime Environment (build 1.8.0_144-b01)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)`
2. picardtools was run with success.
3. After editing the gridss.sh file, I run the script and getting the error that is present at the end of file `slurm-2488298.out` (attached). I have also attached the modified gridss.sh script.
4. I do not understand it.

Regards,
Kostas

[gridss.txt](https://github.com/PapenfussLab/gridss/files/4558645/gridss.txt)
[slurm-2488298.txt](https://github.com/PapenfussLab/gridss/files/4558646/slurm-2488298.txt)

**Comment by d-cameron** [comment] 2020-05-02 05:15
Likely root cause is mismatch with htsjdk/picard implementation override classes. Working on a fix.

**Comment by d-cameron** [comment] 2020-05-12 13:14
v2.9.1 released with latest htsjdk and picard libraries.

The other option I can think of is that you have additional classes in your classpath. If you have a version of htsjdk or picard in classpath, and these override the GRIDSS versions, then I can see how this error could occur. See https://github.com/samtools/htsjdk/pull/1249 for the files that are patched directly in GRIDSS.

**Comment by kostasgalexiou** [comment] 2020-05-16 21:53
Working like a charm!

Thanks a lot!

**Comment by kostasgalexiou** [comment] 2020-06-02 06:59
Hi d-cameron,

I have installed gridss-2.9.2 using conda. File `./info/test/run_test.sh` exits without errors, but still getting the "exit code 6" error.

I run the following commands.

-  Setup reference:

        `~/.conda/envs/gridss-2.9.2/share/gridss-2.9.2-0/gridss.sh \
        -r /projects/061-SECUENCIAS-Pd_Pp/Reference/Peach_V2_release/genome/v2.1_gdr/Prunus_persica_main_genome_scaffolds.fasta \
        -o test.gridss.vcf \
        -j ~/.conda/envs/gridss-2.9.2/share/gridss-2.9.2-0/gridss.jar \
        -s setupreference \
        -w gridss_tempdir\
        -l EG2 
        --nojni 
        ./EG2.sort.bam`

Commands exits without errors, but is gives me the following warning:

            `basename: missing operand`
            `Try 'basename --help' for more information.`

- Preprocess:

        `~/.conda/envs/gridss-2.9.2/share/gridss-2.9.2-0/gridss.sh \
        -r /projects/061-SECUENCIAS-Pd_Pp/Reference/Peach_V2_release/genome/v2.1_gdr/Prunus_persica_main_genome_scaffolds.fasta \
        -o test.gridss.vcf \
        -j ~/.conda/envs/gridss-2.9.2/share/gridss-2.9.2-0/gridss.jar \
        -s setupreference \
        -w gridss_tempdir\
        -l EG2 
        --nojni 
        ./EG2.sort.bam`

I am still getting the "basename" warning mentioned above. Below is the screen output with the "exit code 6" error at the end.

Using working directory "gridss_tempdir"
Tue Jun  2 08:28:29 CEST 2020: Full log file is: gridss_tempdir/gridss.full.20200602_082829.huberman.42000.log
Tue Jun  2 08:28:29 CEST 2020: Found /usr/bin/time
Tue Jun  2 08:28:29 CEST 2020: Using reference genome "/projects/061-SECUENCIAS-Pd_Pp/Reference/Peach_V2_release/genome/v2.1_gdr/Prunus_persica_main_genome_scaffolds.fasta"
Tue Jun  2 08:28:29 CEST 2020: Using 8 worker threads.
Tue Jun  2 08:28:29 CEST 2020: Using no blacklist bed. The encode DAC blacklist is recommended for hg19.
Tue Jun  2 08:28:29 CEST 2020: Using JVM maximum heap size of 25g for assembly and variant calling.
Tue Jun  2 08:28:29 CEST 2020: Using input file ./EG2.sort.bam
Tue Jun  2 08:28:29 CEST 2020: label is EG2
basename: missing operand
Try 'basename --help' for more information.
Tue Jun  2 08:28:29 CEST 2020: Found /home/kalexiou/.conda/envs/gridss-2.9.2/bin/Rscript
Tue Jun  2 08:28:29 CEST 2020: Found /home/kalexiou/.conda/envs/gridss-2.9.2/bin/samtools
Tue Jun  2 08:28:29 CEST 2020: Found /home/kalexiou/.conda/envs/gridss-2.9.2/bin/java
Tue Jun  2 08:28:29 CEST 2020: samtools version: 1.10+htslib-1.10.2
Tue Jun  2 08:28:30 CEST 2020: R version: R scripting front-end version 3.6.1 (2019-07-05)
Tue Jun  2 08:28:30 CEST 2020: bwa Version: 0.7.17-r1188
Tue Jun  2 08:28:30 CEST 2020: time version: GNU time 1.7
Tue Jun  2 08:28:30 CEST 2020: bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Tue Jun  2 08:28:31 CEST 2020: java version: openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)
Tue Jun  2 08:28:31 CEST 2020: Max file handles: 131072
Tue Jun  2 08:28:31 CEST 2020: Running GRIDSS steps: preprocess,
Tue Jun  2 08:28:32 CEST 2020: Disabling snappy, GKL, SSW, and in-process BWA
Tue Jun  2 08:28:32 CEST 2020: Start pre-processing     ./EG2.sort.bam
Tue Jun  2 08:28:32 CEST 2020: Running  CollectInsertSizeMetrics        ./EG2.sort.bam  first 10000000 records
"$timecmd java -Xmx4g $jvm_args -cp $gridss_jar gridss.analysis.CollectGridssMetrics TMP_DIR=$dir ASSUME_SORTED=true I=$f O=$tmp_prefix THRESHOLD_COVERAGE=$maxcoverage FILE_EXTENSION=null GRIDSS_PROGRAM=null PROGRAM=null PROGRAM=CollectInsertSizeMetrics STOP_AFTER=$metricsrecords $picardoptions" command completed with exit code 6.

I followed the link that you sent me about the files directly patched to GRIDSS but I could follow it....Sorry.

Any help will be appreciated.

Thanks
Kostas

**Closed** 2020-08-06 04:42 UTC
Labels: bug

**Comment by kostasgalexiou** [comment] 2021-09-28 12:32
Hi d-cameron,

I have decided to use the last version of gridss (2.12.1) and see whether the error of "exit code 6" was still appearing or not. According to the [gridss full log file](https://drive.google.com/file/d/1dOlyShKtJs0mSz6LyjTj0Ihe6nfExipJ/view?usp=sharing)  and the [slurm log file](https://drive.google.com/file/d/1_ECVpfQhFZVTaU3dkieRxbHKWPa6oeDd/view?usp=sharing), I am getting the same "exit code 6" error. Do you think that this is a gridss-related error?

I am also attaching the bash file that I am launching with sbatch: [gridss.sh](https://drive.google.com/file/d/1ysL31oZEz57ttm1U--dZ-eh9bH3rnjcu/view?usp=sharing)

Many thanks,
Kostas
