### ISSUE TITLE
SupportNodeIterator error leading to PositionalAssembler failure -- kmer out of bounds

### ISSUE THREAD

**Issue by GWheelerEB** [PapenfussLab/gridss#388] opened 2020-08-26 15:52 UTC
Trying to run GRIDSS, I have been running into a collection of errors that I haven't been able to figure out after quite a bit of time spent working on it. I have been able to run GRIDSS without issue on simulated 30X WGS data, and I have also been able to run it successfully on the same data I'm using here (NA24385 WGS) downsampled to 1%. Because of this, I can't help but think it's a resource issue, but increasing the memory-per-CPU substantially has not helped, and none of the errors really suggest anything about lack of resources. (This is being run within a Docker container in an AWS EC2 instance, but so were the successful runs.)

There are a few notable errors from the log file, which I will include here. First:

```
> ERROR	2020-08-26 13:52:49	SupportNodeIterator	Error: kmer in evidence jcrrKA11S0aMM7f816XBWg8OP5kT7GPC of read A00498:96:HMTWGDMXX:1:2244:28962:18928 (6:165852744 136S5M) out of bounds. Kmer support starts at 165851895 which is more than 848 before the breakpoint start position at <(5):165852744 (5):165852743>
```
(This type of error appears 124,119 times)

Then, leading to the final failure of the program:

```
> ERROR	2020-08-26 13:56:23	PositionalAssembler	Error assembling 7. Please raise an issue at https://github.com/PapenfussLab/gridss/issues. If your data can be shared publicly, please also include a minimal data set for reproducing the problem by attaching /data/ede6c9e590af4212ae12f01e98fd83d1/temp/gridss_minimal_reproduction_data_for_error_1103.zip.. Attempting recovery by resuming assembly at 7:12473654
java.lang.RuntimeException: Sanity check failure: found path with no support (7:12459684)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:666)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:231)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:261)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:195)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:76)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:250)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:103)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:114)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:61)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:198)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
(This type of error appears 1,103 times)

I've attached the logs and minimal-data ZIP file. Any advice on this issue would be greatly appreciated.

[gridss.logs.zip](https://github.com/PapenfussLab/gridss/files/5130943/gridss.logs.zip)
[gridss_minimal_reproduction_data_for_error_1103.zip](https://github.com/PapenfussLab/gridss/files/5130936/gridss_minimal_reproduction_data_for_error_1103.zip)

**Comment by d-cameron** [comment] 2020-09-04 06:23
Duplicate of #314. Already fixed in dev branch.

**Closed by d-cameron** 2020-09-04 06:23 UTC
Labels: duplicate
