### ISSUE TITLE
Somatic filter error

### ISSUE THREAD

**Issue by andreyurch** [PapenfussLab/gridss#431] opened 2020-11-30 10:46 UTC
Dear developers, I encountered an error during work with somatic filter for human samples.  Before I tried with mice and everything worked perfectly.

Rscript gridss_somatic_filter.R --ref BSgenome.Hsapiens.UCSC.hg19 --normalordinal 1 --tumourordinal 2 --input test.pass.vcf --output test.somatic.vcf

Loading required package: BSgenome
2020-11-30 11:43:57 Reading test.pass.vcf
Tumour samples: xFD03_F015P01_T01_AML_D1_x
Matched normals: xFD03_F015P01_N02_fibro_D1_x
2020-11-30 11:44:06 Parsing single breakends test.pass.vcf
2020-11-30 11:44:07 Calculating single breakend VAF test.pass.vcf
2020-11-30 11:44:07 Filtering single breakends test.pass.vcf
2020-11-30 11:44:08 Parsing breakpoints test.pass.vcf
2020-11-30 11:44:09 Calculating breakpoint VAF test.pass.vcf
2020-11-30 11:44:09 Filtering breakpoints test.pass.vcf
Warning message:
In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chrMT, chr4_ctg9_hap1, chr6_apd_hap1, chr6_cox_hap2, chr6_dbb_hap3, chr6_mann_hap4, chr6_mcf_hap5, chr6_qbl_hap6, chr6_ssto_hap7, chr17_ctg5_hap1, chr1_gl000191_random, chr1_gl000192_random, chr4_gl000193_random, chr4_gl000194_random, chr7_gl000195_random, chr8_gl000196_random, chr8_gl000197_random, chr9_gl000198_random, chr9_gl000199_random, chr9_gl000200_random, chr9_gl000201_random, chr11_gl000202_random, chr17_gl000203_random, chr17_gl000204_random, chr17_gl000205_random, chr17_gl000206_random, chr18_gl000207_random, chr19_gl000208_random, chr19_gl000209_random, chr21_gl000210_random, chrUn_gl000211, chrUn_gl000212, chrUn_gl000213, chrUn_gl000214, chrUn_gl000215, chrUn_gl000216, chrUn_gl000217, chrUn_gl000218, chrUn_gl000219, chrUn_gl000220, chrUn_gl000221, chrUn_gl000222, chrUn_gl000223, chrUn_gl000224, chrUn_gl000225, chrUn_gl000226, chrUn_gl000227, chrUn_gl000228, chrUn_gl000229, chrUn_gl000230, chr [... truncated]
2020-11-30 11:44:11 Calculating transitive links test.pass.vcf
2020-11-30 11:44:11 Calculating assembly links test.pass.vcf
`summarise()` ungrouping output (override with `.groups` argument)
2020-11-30 11:44:12 Calculating bebe insertion links test.pass.vcf
2020-11-30 11:44:12 Calculating bebp insertion links test.pass.vcf
2020-11-30 11:44:12 Calculating simple inversions test.pass.vcf
2020-11-30 11:44:12 Calculating dsb links test.pass.vcf
2020-11-30 11:44:12 Removing duplicated/conflicting links test.pass.vcf
Error: Can't subset elements that don't exist.
✖ Location 1 doesn't exist.
ℹ There are only 0 elements.
Backtrace:
     █
  1. ├─`%>%`(...)
  2. │ ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  3. │ └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  4. │   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5. │     └─`_fseq`(`_lhs`)
  6. │       └─magrittr::freduce(value, `_function_list`)
  7. │         └─function_list[[i]](value)
  8. │           ├─dplyr::mutate(...)
  9. │           └─dplyr:::mutate.data.frame(...)
 10. │             └─dplyr:::mutate_cols(.data, ...)
 11. │               ├─base::withCallingHandlers(...)
 12. │               └─mask$eval_all_mutate(dots[[i]])
 13. ├─base::.signalSimpleWarning(...)
 14. │ └
Execution halted

**Comment by yu052** [comment] 2020-12-16 14:48
I also got similar error for some of my samples. But the script worked perfectly for other samples. Any clue for this error?

**Comment by willhooper** [comment] 2020-12-21 14:26
Hi, I'm getting the same error for human samples called in single-sample mode.

**Comment by d-cameron** [comment] 2021-01-01 13:49
Duplicate of #390 and fixed on 2020-09-03 so should be working from v2.10.0 onwards.

**Closed by d-cameron** 2021-01-01 13:49 UTC
