### ISSUE TITLE
An error when starting gridss

### ISSUE THREAD

**Issue by charliechen912ilovbash** [PapenfussLab/gridss#470] opened 2021-03-14 04:19 UTC
```
Wed Mar 10 13:04:53 UTC 2021: Full log file is: /home/joe/cancer/short_sv/gridss/sample/gridss.full.20210310_
130453.yc138.11268.log
Wed Mar 10 13:04:53 UTC 2021: Found /usr/bin/time
Wed Mar 10 13:04:53 UTC 2021: Using GRIDSS jar /opt/gridss/gridss-2.10.2-gridss-jar-with-dependencies.jar
Wed Mar 10 13:04:53 UTC 2021: Using reference genome "/home/joe/reference/other/GDC_GRCh38_plus_AAV2/GDC-GRCh38_
plus_AAV2.fa"
Wed Mar 10 13:04:53 UTC 2021: Using assembly bam  /home/joe/cancer/short_sv/gridss/sample/sample-T_ass.bam
Wed Mar 10 13:04:53 UTC 2021: Using output VCF /home/joe/cancer/short_sv/gridss/sample/sample-T.vcf.gz
Wed Mar 10 13:04:53 UTC 2021: Using 8 worker threads.
Wed Mar 10 13:04:53 UTC 2021: Using no blacklist bed. The encode DAC blacklist is recommended for hg19.
Wed Mar 10 13:04:53 UTC 2021: Using JVM maximum heap size of 32m for assembly and variant calling.
Wed Mar 10 13:04:53 UTC 2021: Using input file /home/joe/cancer/genomonsv/confirm_sampleH72/sample-T.bam
Wed Mar 10 13:04:53 UTC 2021: label is sample-T
Wed Mar 10 13:04:53 UTC 2021: Found /bins/miniconda3/envs/R4/bin/Rscript
Wed Mar 10 13:04:53 UTC 2021: Found /usr/bin/samtools
Wed Mar 10 13:04:53 UTC 2021: Found /usr/bin/java
Wed Mar 10 13:04:53 UTC 2021: Found /usr/bin/bwa
Wed Mar 10 13:04:53 UTC 2021: samtools version: 1.7+htslib-1.7-2
Wed Mar 10 13:04:53 UTC 2021: R version: R scripting front-end version 4.0.3 (2020-10-10)
Wed Mar 10 13:04:53 UTC 2021: bwa Version: 0.7.17-r1188
Wed Mar 10 13:04:53 UTC 2021: time version: GNU time 1.7
Wed Mar 10 13:04:53 UTC 2021: bash version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Wed Mar 10 13:04:54 UTC 2021: java version: Picked up JAVA_TOOL_OPTIONS: -XX:+UseSerialGC -Xmx64m -Xms32m       open
jdk version "1.8.0_275"     OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)      OpenJDK
64-Bit Server VM (build 25.275-b01, mixed mode)
Wed Mar 10 13:04:54 UTC 2021: Max file handles: 131070
Wed Mar 10 13:04:54 UTC 2021: Running GRIDSS steps: setupreference, preprocess, assemble, call,
Wed Mar 10 13:04:54 UTC 2021: Running   PrepareReference        (once-off setup for reference genome)
Picked up JAVA_TOOL_OPTIONS: -XX:+UseSerialGC -Xmx64m -Xms32m
INFO    2021-03-10 13:04:54     Defaults        Found file for property samjdk.reference_fasta: /home/joe/reference/other/GDC_GRCh38_plus_AAV2/GDC-GRCh38_plus_AAV2.fa
INFO    2021-03-10 13:04:54     PrepareReference

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    PrepareReference -REFERENCE_SEQUENCE /home/joe/reference/other/GDC_GRCh38_plus_AAV2/GDC-GRCh38_plus_AAV2.fa
**********


13:04:54.564 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/gridss/gridss-2.10.2-gridss-jar-with-dependencies.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Mar 10 13:04:54 UTC 2021] PrepareReference REFERENCE_SEQUENCE=/home/joe/reference/other/GDC_GRCh38_plus_AAV2/GDC-GRCh38_plus_AAV2.fa    CREATE_SEQUENCE_DICTIONARY=true CREATE_GRIDSS_REFERENCE_CACHE=true CREATE_BWA_INDEX_IMAGE=true VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Mar 10 13:04:54 UTC 2021] Executing as joe@yc138i on Linux 3.10.0-1127.18.2.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.10.2-gridss
INFO    2021-03-10 13:04:54     PrepareReference        Sequence dictionary found.
INFO    2021-03-10 13:04:54     PrepareReference        Creating GRIDSS reference cache file /home/joe/reference/other/GDC_GRCh38_plus_AAV2/GDC-GRCh38_plus_AAV2.fa.gridsscache
ERROR   2021-03-10 13:04:54     PrepareReference
java.lang.IllegalArgumentException: Reference genome does not have an index. Create using `samtools faidx`.
        at au.edu.wehi.idsv.picard.TwoBitBufferedReferenceSequenceFile.<init>(TwoBitBufferedReferenceSequenceFile.java:34)
        at au.edu.wehi.idsv.picard.TwoBitBufferedReferenceSequenceFile.<init>(TwoBitBufferedReferenceSequenceFile.java:30)
        at gridss.PrepareReference.doWork(PrepareReference.java:47)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at gridss.PrepareReference.main(PrepareReference.java:89)
[Wed Mar 10 13:04:54 UTC 2021] gridss.PrepareReference done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=32440320
```

Is this related to Picard version?
And also another thing is that, I need to set `--jvmheap 32m` or it will show `Initial heap size set to a larger value than the maximum heap size` . 

Thanks a lot!

Joe

**Comment by alexiswl** [comment] 2021-03-14 04:24
Hi @charliechen912ilovbash 

See this line here:
> java.lang.IllegalArgumentException: Reference genome does not have an index. Create using `samtools faidx`.

Please run `samtools faidx /home/joe/reference/other/GDC_GRCh38_plus_AAV2/GDC-GRCh38_plus_AAV2.fa` to generate the fasta index file `/home/joe/reference/other/GDC_GRCh38_plus_AAV2/GDC-GRCh38_plus_AAV2.fa.fai`.  

> And also another thing is that, I need to set --jvmheap 32m or it will show Initial heap size set to a larger value than the maximum heap size .

What system are you running this on? 32m seems very small

**Comment by charliechen912ilovbash** [comment] 2021-03-14 04:44
Hi,
Thanks for reply.
I noticed the `java.lang.IllegalArgumentException: Reference genome does not have an index. Create using samtools faidx.`
However, there is already an index file `GDC-GRCh38_plus_AAV2.fa.fai` generated by `samtools faidx GDC-GRCh38_plus_AAV2.fa`.
I am using a supercomputer at school, but I don't know why Xms should be set to so small.

This is the command I used:
```
sample="sample-T"
sampleID="sample"
out="/home/joe/cancer/short_sv/gridss/${sampleID}/"
ref="/home/joe/reference/other/GDC_GRCh38_plus_AAV2/GDC-GRCh38_plus_AAV2.fa"
bam="/home/joe/cancer/confirm_sample/${sample}.bam"
threads="8"
gridss.sh --reference  ${ref} --output ${out}${sample}.vcf.gz --assembly ${out}${sample}_ass.bam --threads ${threads} --jar /opt/gridss/gridss-2.10.2-gridss-jar-with-dependencies.jar --workingdir ${out}  --steps All --jvmheap 32m --picardoptions VALIDATION_STRINGENCY=LENIENT  --labels ${sample} ${bam}
```

I run GRIDSS in singularity image. I get the singularity image from:` gridss/gridss:latest`, then I add the tools seems to be lack in the image, including: kraken2, repeatmasker, bcftools, htslib. I install these tools with conda.

This is the singularity definition file:
```
BootStrap: docker
From: gridss/gridss:latest
#From: ubuntu:latest #18.04 or 20.04
%environment
    PATH="/home/$USER/.local/bin:/opt/gridss:/bins/miniconda3/bin/:/bins/miniconda3/envs/R4/bin:/bins/miniconda3/envs/kraken2/bin:/bins/miniconda3/envs/repeatmasker/bin:/bins/miniconda3/envs/bcftools/bin:/bins/miniconda3/envs/htslib/bin:$PATH"
    export PATH
%post
    mkdir /bins/
%files
    set_alias_short-prompt_folder-color.sh
    /home/charlie/work/singularity/set_alias_short-prompt_folder-color.sh /opt
%post
    apt-get update -y
    apt-get install htop wget vim man-db manpages-posix manpages-dev   -y
    cd /bins/
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    sh Miniconda3-latest-Linux-x86_64.sh -b -p /bins/miniconda3
    export PATH=/bins/miniconda3/bin/:$PATH
    conda init
    chmod 744 ~/.bashrc
    sed 's/shopt -s/#shopt -s/g' ~/.bashrc > ~/.bashrcc 
    mv ~/.bashrcc ~/.bashrc
    cp ~/.bashrc /bins/.bashrc
    cat /opt/set_alias_short-prompt_folder-color.sh >> /bins/.bashrc
    . /bins/.bashrc
    conda create -c conda-forge -n R4 r-base -y
    conda create -c conda-forge -c bioconda -n kraken2 kraken2 -y
    conda create -c conda-forge -c bioconda -n repeatmasker repeatmasker -y
    conda create -c conda-forge -c bioconda -n bcftools bcftools -y
    conda create -c conda-forge -c bioconda -n htslib htslib -y
```

**Comment by alexiswl** [comment] 2021-03-14 09:16
Ah I see, can you send through the singularity command you are using to run the script? It could be that you're mounting the reference file rather than the reference directory.  

You also shouldn't need to do anything to the dockerfile in order for it to run on singularity.  

In order to override the entrypoint you can either do the following:

1. Build the image but reset the entrypoint

```bash
BootStrap: docker
From: gridss/gridss:latest

%runscript
/opt/gridss/gridss.sh
```

2. Use the gridss quay.io container:
```
singularity pull gridss.sif quay.io/biocontainers/gridss:2.10.2--0
```

This won't even need the sudo permissions in order to run and `gridss` should already be in the path.  

```
singluarity run \
  --bind /path/to/ref-dir:/path/to/ref-dir/ \
  --bind /path/to/input-data/:/path/to/input-data/ \
  --bind /path/to/workdir/:/path/to/workdir \
  --workdir /path/to/workdir/ \
  gridss.sif \
    gridss \
      --ref /path/to/ref-dir/ref.fa \
      --workingdir /path/to/workdir/out/ \
      /path/to/input-dir/input.bam
```

You should try again without setting the jvmheap value.  The --jar parameter should also then be omitted.

**Comment by charliechen912ilovbash** [comment] 2021-03-14 11:00
I use `singularity shell  image.simg` to enter the environment, then run the `gridss.sh` in the environment. 
Thanks for your advice!! I am trying it.

**Comment by charliechen912ilovbash** [comment] 2021-03-16 00:04
Hi, 
Thanks for reply, I have tried your suggestion commands, but the same error message, `java.lang.IllegalArgumentException: Reference genome does not have an index. Create using `samtools faidx`  came out. 
If not set `--jvmheap` , then it shows `Failure invoking java with --jvmheap parameter of "30g". Specify a JVM heap size (e.g. "31g") that is valid for this machine.`
Maybe it is not singularity's problem ?
I am not sure but I am considering about Picard

**Comment by alexiswl** [comment] 2021-03-16 00:27
Can you send through the singularity build and singularity run commands you've used please?

**Comment by charliechen912ilovbash** [comment] 2021-03-16 01:37
Sure:
`singularity build gridss.simg gridss.def`
The `gridss.def` is the same as you suggested:
```
BootStrap: docker
From: gridss/gridss:latest

%runscript
/opt/gridss/gridss.sh "$@"
```

```
sampleID="A01"
out="/home/joe/cancer/gridss/${sampleID}/"
refd="/home/joe/reference/other/GDC_GRCh38/"
bamd="/home/joe/cancer/bam/"
bam="A01.bam"

singularity run \
  --bind ${refd}:${refd} \
  --bind ${bamd}:${bamd} \
  --bind ${out}:${out} \
  --workdir ${out} \
  ~/short-read_sv_caller_gridss_official.simg \
    /opt/gridss/gridss.sh \
      --reference ${ref} \
      --workingdir ${out} \
      --jar /opt/gridss/gridss-2.10.2-gridss-jar-with-dependencies.jar \
      --assembly ${out}${sampleID}_ass.bam \
      --output ${out}${sampleID}.vcf.gz \
      --steps All \
      --labels ${sampleID} \
      --jvmheap 32m \
      ${bam}
```
This command will get `no faidx` error
If remove `--jvmheap` option, then `Failure invoking java with --jvmheap parameter of "30g"` will show up
The first I tried with `singularity shell` as mention before, and later I also have tried `gridss 2.10.1` but the same error message came out for both times.

**Comment by alexiswl** [comment] 2021-03-16 02:59
Thanks for this, sorry this is happening to you but it's likely a singularity configuration on your system and not overlaying bind paths in a writable format:

Try the following: 

Bind the `/home/joe/reference/other/GDC_GRCh38/` directory and shell into the container with

```
singularity shell \
  --bind "/home/joe/reference/other/GDC_GRCh38/:/home/joe/reference/other/GDC_GRCh38/" \
  ~/short-read_sv_caller_gridss_official.simg
```

Then try touching a non-existant file inside that directory from inside the container

```
touch /home/joe/reference/other/GDC_GRCh38/
samtools faidx /home/joe/reference/other/GDC_GRCh38_plus_AAV2/GDC-GRCh38_plus_AAV2.fa
```

If these don't work you'll need to discuss with your sysadmin about enabling `overlay` with singularity.  See [the sningularity docs](https://singularity-admindoc.readthedocs.io/en/latest/the_singularity_config_file.html#user-bind-control-boolean-default-yes) for more information

**Comment by charliechen912ilovbash** [comment] 2021-03-16 17:27
Thanks for suggestion! I tried above but still got `no faidx` error. I will discuss with sysadmin. By the way, the `singularity` on the server is quite old, 2.6.1. Do you think this can be one of the reason?

**Comment by d-cameron** [comment] 2021-03-16 22:20
Is the reference data mount point writeable? the gridss `--setupreference` step creates a set of reference index files if they don't exist. This is a once-off step and requires the reference data mount point to the writeable. Once those files are written it can be mounted read-only for all subsequent runs using that reference genome.

**Comment by alexiswl** [comment] 2021-03-16 23:20
> By the way, the singularity on the server is quite old, 2.6.1. Do you think this can be one of the reason?

Yes, I'd consider upgrading to a later version of singularity which has better support for docker files. You should just be able to pull the docker image from dockerhub as a singularity image without having to write a singularity recipe.  

> Thanks for suggestion! I tried above but still got no faidx error

What were the outputs of 

```
touch /home/joe/reference/other/GDC_GRCh38/foo
samtools faidx /home/joe/reference/other/GDC_GRCh38_plus_AAV2/GDC-GRCh38_plus_AAV2.fa
```

from inside the singularity container?

**Comment by charliechen912ilovbash** [comment] 2021-03-17 16:46
```
touch /home/joe/reference/other/GDC_GRCh38/foo
samtools faidx /home/joe/reference/other/GDC_GRCh38_plus_AAV2/GDC-GRCh38_plus_AAV2.fa
```
Both finished successfully without error message. The  `/home/joe/reference/other/GDC_GRCh38_plus_AAV2/GDC-GRCh38_plus_AAV2.fa.fai` was generated in the same folder. 
But later I run gridss.sh still got the `no faidx` error message.

**Comment by d-cameron** [comment] 2021-03-18 08:15
>      --jvmheap 32m

That heap is approximately 1000 times too small.

You should explicitly specify `--threads`.

> If remove --jvmheap option, then Failure invoking java with --jvmheap parameter of "30g" will show up

How much memory does your singularity instance have access to? The root cause might just be not enough memory.

**Comment by d-cameron** [comment] 2021-03-30 03:55
> And also another thing is that, I need to set --jvmheap 32m or it will show Initial heap size set to a larger value than the maximum heap size.

Closing as it looks very much like the container doesn't have enough memory to run GRIDSS (or possibly even some of the `samtools` commands)

**Closed by d-cameron** 2021-03-30 03:55 UTC
