### ISSUE TITLE
rsync_from_ncbi.pl: unexpected FTP path (new server?) for na

### ISSUE THREAD

**Issue by MjelleLab** [PapenfussLab/gridss#540] opened 2021-11-04 15:35 UTC
I get the following error below.

I have replaced line 46 in the rsync_from_ncbi.pl but it did not solve the error:

if (! ($full_path =~ s#^ftp://${qm_server}${qm_server_path}/##)) {
to
if (! ($full_path =~ s#^https://${qm_server}${qm_server_path}/##)) {

ERROR: 

~/software/VIRUSBreakend$ ./virusbreakend-build --db virusbreakenddb_20210401 --jar ./gridss-2.12.2-gridss-jar-with-dependencies.jar
Thu Nov  4 16:10:24 MET 2021: Found /home/local/robinm/software/kraken2/kraken2-2.0.8-beta/kraken2-build
Thu Nov  4 16:10:24 MET 2021: Found /home/local/robinm/anaconda3/envs/krakenuniq/bin/samtools
Thu Nov  4 16:10:24 MET 2021: Found /bin/gunzip
Thu Nov  4 16:10:24 MET 2021: Found /home/local/robinm/anaconda3/envs/krakenuniq/bin/tar
Thu Nov  4 16:10:24 MET 2021: Found /home/local/robinm/anaconda3/envs/krakenuniq/bin/dustmasker
Thu Nov  4 16:10:24 MET 2021: Found /home/local/robinm/anaconda3/envs/krakenuniq/bin/rsync
Thu Nov  4 16:10:24 MET 2021: Found /home/local/robinm/anaconda3/envs/krakenuniq/bin/java
Thu Nov  4 16:10:24 MET 2021: Found /home/local/robinm/anaconda3/envs/krakenuniq/bin/wget
Thu Nov  4 16:10:24 MET 2021: Using GRIDSS jar ./gridss-2.12.2-gridss-jar-with-dependencies.jar
mv: replace 'assembly_summary.txt', overriding mode 0444 (r--r--r--)? y
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 1 project (639 sequences, 3.27 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 11586 projects (14461 sequences, 454.70 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Downloading UniVec_Core data from server... done.
Adding taxonomy ID of 28384 to all sequences... done.
Masking low-complexity regions of downloaded library... done.
rsync_from_ncbi.pl: unexpected FTP path (new server?) for na
"kraken2-build $kraken2buildargs --download-library bacteria --db $dbname" command completed with exit code 25.

**Comment by d-cameron** [comment] 2021-11-05 07:09
Underlying issue is in `kraken2-build` talking to NCBI.

Duplicate of https://github.com/DerrickWood/kraken2/issues/525

**Closed by d-cameron** 2021-11-05 07:09 UTC

**Comment by d-cameron** [comment] 2021-11-05 07:10
Note that there is a pre-built VIRUSBreakend database available for download so you don't need to run `virusbreakend-build` yourself.   See https://github.com/PapenfussLab/gridss/blob/master/VIRUSBreakend_Readme.md#reference-data for the link to download the VIRUSBreakend database from an AWS mirror.

**Comment by MjelleLab** [comment] 2021-11-05 07:16
Oh, thanks, Didn't notice the pre-build.
Thanks,

**Comment by MjelleLab** [comment] 2021-11-05 07:19
Using the prebuild I get this error:

Unable to find virusbreakenddb_20210401/taxid10239.nbr.

----

Robin Mjelle
PhD
Department of Cancer Research and Molecular Medicine
Faculty of Medicine
Laboratory Centre, 5th floor. Erling Skjalgssons gt. 1
Norwegian University of Science and Technology NTNU
7030 Trondheim, Norway
Cell. phone: +47 40234780

**Comment by xiaoyunguo** [comment] 2021-12-01 17:51
I have the same problem with kraken2-build, any solution to this?
