### ISSUE TITLE
stream closed in gridss run

### ISSUE THREAD

**Issue by alkodsi** [PapenfussLab/gridss#31] opened 2016-07-01 09:39 UTC
I am getting this error in one of my samples:

ERROR   2016-06-30 10:18:24     SAMEvidenceSource       
htsjdk.samtools.util.RuntimeIOException: Stream Closed
        at htsjdk.samtools.util.BinaryCodec.close(BinaryCodec.java:610)
        at htsjdk.samtools.util.BlockCompressedOutputStream.close(BlockCompressedOutputStream.java:227)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
        at htsjdk.samtools.util.BinaryCodec.close(BinaryCodec.java:606)
        at htsjdk.samtools.BAMFileWriter.finish(BAMFileWriter.java:136)
        at htsjdk.samtools.SAMFileWriterImpl.close(SAMFileWriterImpl.java:219)
        at htsjdk.samtools.util.CloserUtil.close(CloserUtil.java:64)
        at htsjdk.samtools.util.CloserUtil.close(CloserUtil.java:48)
        at au.edu.wehi.idsv.pipeline.ExtractEvidence.close(ExtractEvidence.java:71)
        at au.edu.wehi.idsv.pipeline.ExtractEvidence.doProcess(ExtractEvidence.java:192)
        at au.edu.wehi.idsv.pipeline.ExtractEvidence.process(ExtractEvidence.java:135)
        at au.edu.wehi.idsv.SAMEvidenceSource.completeSteps(SAMEvidenceSource.java:91)
        at au.edu.wehi.idsv.Idsv$2$1.call(Idsv.java:375)
        at au.edu.wehi.idsv.Idsv$2$1.call(Idsv.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Stream Closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at htsjdk.samtools.util.BinaryCodec.close(BinaryCodec.java:595)
        ... 17 more

**Comment by d-cameron** [comment] 2016-07-03 09:09
Thank you for the report.

There was a race condition identified that would cause errors on close(). This has already been fixed in https://github.com/PapenfussLab/gridss/releases/tag/v0.11.5 so I recommend you try with that version.

Note that this issue does not effect correctness, and only occurs occasionally. GRIDSS is designed to be rerunnable and will continue at the step it left off at (if the intermediate files have not been deleted since it was run).

**Comment by alkodsi** [comment] 2016-07-05 09:29
I tried the new version 0.11.5 and I got the same error

**Comment by d-cameron** [comment] 2016-07-09 01:03
Are you able to attach a copy of the GRIDSS log file of the failed run. If possible rerunning with VERBOSITY=DEBUG as an additional command-line argument would help immensely with identifying the root cause of the error.

**Comment by alkodsi** [comment] 2016-07-11 09:27
I reran the analysis and it worked this time without problems.

**Closed** 2016-07-21 00:25 UTC
