### ISSUE TITLE
Sort Failure During Preprocess Returns Exit Code 0

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#477] opened 2021-03-24 06:00 UTC
I have some strange goings on.

```
$ tail /scratch/hm82/temporary/gridss.full.20210324_114249.gadi-cpu-clx-1008.gadi.nci.org.au.640182.log
INFO    2021-03-24 14:35:53     StreamingSplitReadRealigner     Processed   269,000,000 records.  Elapsed time: 01:29:25s.  Time for last 1,000,000:   51s.  Last read position: chr13:63,441,360.  Last read name: A00119:326:HNV7LDSXY:3:2673:26847:24690
INFO    2021-03-24 14:36:08     TwoBitBufferedReferenceSequenceFile     Caching reference genome contig chrUn_KN707696v1_decoy
INFO    2021-03-24 14:36:08     TwoBitBufferedReferenceSequenceFile     Caching reference genome contig chrUn_JTFH01000181v1_decoy
INFO    2021-03-24 14:36:09     StreamingSplitReadRealigner     Processed 270000000 records. 6723 in aligner input buffer. 0 in aligner output buffer. 6232 records in lookup
INFO    2021-03-24 14:36:09     StreamingSplitReadRealigner     Processed   270,000,000 records.  Elapsed time: 01:29:42s.  Time for last 1,000,000:   16s.  Last read position: chr7:23,591,468.  Last read name: A00119:326:HNV7LDSXY:3:2677:12102:10488
[Wed Mar 24 14:36:15 GMT+10:00 2021] gridss.PreprocessForBreakendAssembly done. Elapsed time: 89.83 minutes.
Runtime.totalMemory()=2987917312
[bam_sort_core] merging from 208 files and 8 in-memory blocks...
samtools sort: failed writing to "/scratch/hm82/temporary/CSCC_0136-M1.final.bam.gridss.working/CSCC_0136-M1.final.bam.sv.tmp.bam": Illegal seek
Wed Mar 24 15:49:37 AEDT 2021: pre-processing failed for /scratch/hm82/CSCC//Final_bams/CSCC_0136-M1.final.bam
```

Despite the error, I find the exit status is 0.

```
"exit 1" command completed with exit code 1.

======================================================================================
                  Resource Usage on 2021-03-24 15:49:52:
   Job Id:             19602667.gadi-pbs
   Project:            ts38
   Exit Status:        0
   Service Units:      164.54
   NCPUs Requested:    8                      NCPUs Used: 8
                                           CPU Time Used: 18:29:23
   Memory Requested:   80.0GB                Memory Used: 78.89GB
   Walltime requested: 16:00:00            Walltime Used: 04:06:49
   JobFS requested:    100.0MB                JobFS used: 0B
======================================================================================
```

This leads to the assemble step being started because I use `qsub -W depend=afterok:$preprocessID` and almost immediately failing.

```
======================================================================================
                  Resource Usage on 2021-03-24 15:55:46:
   Job Id:             19602668.gadi-pbs
   Project:            ts38
   Exit Status:        0
   Service Units:      0.03
   NCPUs Requested:    8                      NCPUs Used: 8
                                           CPU Time Used: 00:00:06
   Memory Requested:   80.0GB                Memory Used: 1.27GB
   Walltime requested: 24:00:00            Walltime Used: 00:00:03
   JobFS requested:    100.0MB                JobFS used: 0B
======================================================================================
```

As expected, the preprocessing result file is missing.

```
[Wed Mar 24 14:55:43 GMT+10:00 2021] gridss.AssembleBreakends done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=1622671360
Exception in thread "main" java.lang.IllegalStateException: Missing required file /scratch/hm82/temporary/CSCC_0136-M1.final.bam.gridss.working/CSCC_0136-M1.final.bam.sv.bam. See GRIDSS pipeline examples and documentation.
```

Not sure if I need to upgrade from version 2.9.4.

**Comment by d-cameron** [comment] 2021-03-30 03:27
Duplicate of #479 ? It sounds very much like a file system issue.

**Closed by d-cameron** 2021-03-30 03:27 UTC

**Comment by DarioS** [comment] 2021-03-30 06:00
In case it is important, this problem only happened for the two largest samples in the data set.

```
Sample ID	Average Coverage
CSCC_0066-M1	130
CSCC_0136-M1	132
```

Has GRIDSS been tested on samples with whole genome coverage of about 130 times? It works on others about 105 times or less.

**Comment by d-cameron** [comment] 2021-03-30 07:22
Gridss has been tested to ~1200x human wgs and the latest version to
50,000x coverage with a viral reference genome.  Hartwig uses 40x/100x so
it's been run on over 8000 samples with coverage 130x+
